CREATE OR REPLACE FUNCTION OBTENER_FECHA
RETURN DATE
IS 
    FECHA_ACTUAL DATE;
BEGIN
    SELECT SYSDATE INTO FECHA_ACTUAL FROM DUAL;
    RETURN FECHA_ACTUAL;
END;

CREATE OR REPLACE FUNCTION OBTENER_EDAD(
    FECHA_ENTRADA IN DATE
)
RETURN NUMBER
IS 
    EDAD NUMBER;
BEGIN
    EDAD := TRUNC(MONTHS_BETWEEN(SYSDATE,FECHA_ENTRADA)/12);
    RETURN EDAD;
END;