
-------/\/\     /\/\
--UwU (/ï¿½vï¿½)/ \(ï¿½vï¿½\)
------(    )   (    )
--     v--v     v--v


DROP TABLE CARRO_TEMPORAL;
DROP TABLE DETALLE;
DROP TABLE BOLETA;
DROP TABLE DESPACHO;
DROP TABLE PRODUCTO;
DROP TABLE CATEGORIA;
DROP TABLE REPARTIDOR;
DROP TABLE CLIENTE;


CREATE OR REPLACE TYPE NOMBRE_COMPLETO AS OBJECT(
    NOMBRE VARCHAR2(20),
    APELLIDO VARCHAR2(20)
);

CREATE OR REPLACE TYPE DIRECCION AS OBJECT(
    COMUNA VARCHAR2(50),
    CALLE VARCHAR2(50),
    NUMERO_CASA NUMBER,
    NUMERO_DEPARTAMENTO NUMBER,
    BLOQUE NUMBER
);

CREATE TABLE CLIENTE(
    RUT NUMBER NOT NULL,
    CONTRASE�A VARCHAR(30) NOT NULL,
    ADMINISTRADOR VARCHAR(2),
    NOMBRE_CLIENTE NOMBRE_COMPLETO,
    FECHA_NACIMIENTO DATE,
    TELEFONO NUMBER,
    DIRECCION_CLIENTE DIRECCION,
    CORREO VARCHAR(50)
);

CREATE TABLE REPARTIDOR(
    RUT NUMBER NOT NULL,
    NOMBRE_REPARTIDOR NOMBRE_COMPLETO
);

CREATE TABLE DESPACHO(
    CODIGO_SEGUIMIENTO NUMBER NOT NULL,
    RUT_REPARTIDOR NUMBER NOT NULL,
    RUT_CLIENTE NUMBER NOT NULL,
    TIEMPO_ENTREGA NUMBER,
    ESTADO VARCHAR(50),
    COSTO_DESPACHO NUMBER
);

CREATE TABLE CATEGORIA(
    CODIGO_CATEGORIA NUMBER NOT NULL,
    NOMBRE_CATEGORIA VARCHAR(20)
);

CREATE TABLE PRODUCTO(
    CODIGO_PRODUCTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(30),
    PRECIO NUMBER,
    CODIGO_CATEGORIA NUMBER,
    RESTRINGIDO VARCHAR(2),
    STOCK NUMBER
);

CREATE OR REPLACE TYPE PAGO AS OBJECT(
    NOMBRE_PAGO VARCHAR(50),
    NUMERO_TARJETA NUMBER,
    FECHA_EXPIRACION DATE,
    CVV NUMBER
);

CREATE TABLE BOLETA(
    CODIGO_BOLETA NUMBER NOT NULL,
    CODIGO_SEGUIMIENTO NUMBER NOT NULL,
    FECHA_BOLETA DATE,
    TIPO_PAGO PAGO,
    TOTAL NUMBER
);

CREATE TABLE DETALLE(
    CODIGO_BOLETA NUMBER NOT NULL,
    CODIGO_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER,
    TOTAL NUMBER
);

CREATE TABLE CARRO_TEMPORAL(
    CODIGO_CARRO NUMBER NOT NULL,
    RUT_CLIENTE NUMBER NOT NULL,
    CODIGO_PRODUCTO NUMBER  NOT NULL,
    CANTIDAD NUMBER,
    TOTAL NUMBER
);

ALTER TABLE REPARTIDOR ADD CONSTRAINT PK_REPARTIDOR PRIMARY KEY(RUT);
ALTER TABLE DESPACHO ADD CONSTRAINT PK_DESPACHO PRIMARY KEY(CODIGO_SEGUIMIENTO);
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(RUT);
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY(CODIGO_CATEGORIA);
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTOS PRIMARY KEY(CODIGO_PRODUCTO);
ALTER TABLE BOLETA ADD CONSTRAINT PK_BOLETA PRIMARY KEY(CODIGO_BOLETA);
ALTER TABLE DETALLE ADD CONSTRAINT PK_DETALLE PRIMARY KEY(CODIGO_BOLETA,CODIGO_PRODUCTO);
ALTER TABLE CARRO_TEMPORAL ADD  CONSTRAINT PK_CARRO_TEMPORAL PRIMARY KEY(CODIGO_CARRO);

ALTER TABLE DESPACHO ADD CONSTRAINT FK_DESPACHO_REPARTIDOR FOREIGN KEY(RUT_REPARTIDOR) REFERENCES REPARTIDOR(RUT);
ALTER TABLE DESPACHO ADD CONSTRAINT FK_DESPACHO_CLIENTE FOREIGN KEY(RUT_CLIENTE) REFERENCES CLIENTE(RUT);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY(CODIGO_CATEGORIA) REFERENCES CATEGORIA(CODIGO_CATEGORIA);
ALTER TABLE BOLETA ADD CONSTRAINT FK_BOLETA FOREIGN KEY(CODIGO_SEGUIMIENTO) REFERENCES DESPACHO(CODIGO_SEGUIMIENTO);
ALTER TABLE DETALLE ADD CONSTRAINT FK_DETALLE_BOLETA FOREIGN KEY(CODIGO_BOLETA) REFERENCES BOLETA(CODIGO_BOLETA);
ALTER TABLE DETALLE ADD CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY(CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO);
ALTER TABLE CARRO_TEMPORAL ADD CONSTRAINT FK_CARRO_CLIENTE FOREIGN KEY(RUT_CLIENTE) REFERENCES CLIENTE(RUT);
ALTER TABLE CARRO_TEMPORAL ADD CONSTRAINT FK_CARRO_PRODCUTO FOREIGN KEY(CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO);




