-- CARRO TEMPORAL

CREATE OR REPLACE PROCEDURE ELIMINAR_CARRO(
    CODIGO_ENTRADA IN CARRO_TEMPORAL.CODIGO_CARRO%TYPE,
    MENSAJE OUT VARCHAR
)
IS 
    CODIGO_ES_NULL EXCEPTION;
    CODIGO_INEXISTENTE EXCEPTION;
    REPETICIONES NUMBER;
BEGIN
    LOCK TABLE CARRO_TEMPORAL IN ROW EXCLUSIVE MODE;
    IF CODIGO_ENTRADA IS NULL THEN
        RAISE CODIGO_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICIONES FROM CARRO_TEMPORAL WHERE CODIGO_CARRO = CODIGO_ENTRADA;
        IF REPETICIONES = 0 THEN
            RAISE CODIGO_INEXISTENTE;
        ELSE
            DELETE FROM CARRO_TEMPORAL WHERE CODIGO_CARRO = CODIGO_ENTRADA;
            COMMIT;
            MENSAJE := 'VENTA DE CARRO ELIMINADA';
        END IF;
    END IF;
EXCEPTION
    WHEN CODIGO_ES_NULL THEN
        MENSAJE := 'NO SE INGRESO EL CODIGO DEL CARRO';
        ROLLBACK;
    WHEN CODIGO_INEXISTENTE THEN
        MENSAJE := 'NO EXISTE ESA VENTA EN SU CARRO';
        ROLLBACK;
    WHEN OTHERS THEN
        MENSAJE := 'ERRO NO CAPTURADO EN ELIMINAR VENTA DEL CARRO';
        ROLLBACK;
END;