-- REPARTIDOR

CREATE OR REPLACE PROCEDURE INGRESAR_REPARTIDOR(
    RUT_ENTRADA IN REPARTIDOR.RUT%TYPE,
    NOMBRE_ENTRADA IN REPARTIDOR.NOMBRE_REPARTIDOR.NOMBRE%TYPE,
    APELLIDO_ENTRADA IN REPARTIDOR.NOMBRE_REPARTIDOR.APELLIDO%TYPE,
    MENSAJE OUT VARCHAR 
)
IS
    RUT_ES_NULL EXCEPTION;
    RUT_REPETIDO EXCEPTION;
    PRAGMA EXCEPTION_INIT(RUT_ES_NULL,-20001);
    PRAGMA EXCEPTION_INIT(RUT_REPETIDO,-20002);
    NOMBRE_ES_NULL EXCEPTION;
    APELLIDO_ES_NULL EXCEPTION;
    PRAGMA EXCEPTION_INIT(NOMBRE_ES_NULL,-20004);
    PRAGMA EXCEPTION_INIT(APELLIDO_ES_NULL,-20005);
BEGIN
    LOCK TABLE REPARTIDOR IN ROW EXCLUSIVE MODE;
    INSERT INTO REPARTIDOR VALUES(RUT_ENTRADA,NOMBRE_COMPLETO(NOMBRE_ENTRADA,APELLIDO_ENTRADA));
    COMMIT;
    MENSAJE := 'MIAU REPARTIDOR';
EXCEPTION
    WHEN RUT_ES_NULL THEN
        MENSAJE :='EL RUT ES NULL';
        ROLLBACK;
    WHEN RUT_REPETIDO THEN
        MENSAJE :='EL REPARTIDOR YA ESTA REGISTRADO';
        ROLLBACK;
    WHEN NOMBRE_ES_NULL THEN
        MENSAJE :='EL NOMBRE DEL REPARTIDOR ES NULL';
        ROLLBACK;
    WHEN APELLIDO_ES_NULL THEN
        MENSAJE :='EL APELLIDO DEL REPARTIDOR ES NULL';
        ROLLBACK;
    WHEN OTHERS THEN 
        MENSAJE :='ERROR NO IDENTIFICADO CON EL REPARTIDOR';
        ROLLBACK;
END;


-- CLIENTE

CREATE OR REPLACE PROCEDURE INGRESAR_CLIENTE(
    RUT_ENTRADA IN CLIENTE.RUT%TYPE,
    CONTRASEÑA_ENTRADA IN CLIENTE.CONTRASEÑA%TYPE,
    ADMINISTRADOR_ENTRADA IN CLIENTE.ADMINISTRADOR%TYPE,
    NOMBRE_ENTRADA IN CLIENTE.NOMBRE_CLIENTE.NOMBRE%TYPE,
    APELLIDO_ENTRADA IN CLIENTE.NOMBRE_CLIENTE.APELLIDO%TYPE,
    FECHA_ENTRADA IN CLIENTE.FECHA_NACIMIENTO%TYPE,
    TELEFONO_ENTRADA IN CLIENTE.TELEFONO%TYPE,
    COMUNA_ENTRADA IN CLIENTE.DIRECCION_CLIENTE.COMUNA%TYPE,
    CALLE_ENTRADA IN CLIENTE.DIRECCION_CLIENTE.CALLE%TYPE,
    NUMERO_CASA_ENTRADA IN CLIENTE.DIRECCION_CLIENTE.NUMERO_CASA%TYPE,
    NUMERO_DEPARTAMENTO_ENTRADA IN CLIENTE.DIRECCION_CLIENTE.NUMERO_DEPARTAMENTO%TYPE,
    BLOQUE_ENTRADA IN CLIENTE.DIRECCION_CLIENTE.BLOQUE%TYPE,
    CORREO_ENTRADA IN CLIENTE.CORREO%TYPE,
    MENSAJE OUT VARCHAR
)
IS 
    RUT_ES_NULL EXCEPTION;
    RUT_REPETIDO EXCEPTION;
    PRAGMA EXCEPTION_INIT(RUT_ES_NULL,-20010);
    PRAGMA EXCEPTION_INIT(RUT_REPETIDO,-20011);
    CONSTRASEÑA_ES_NULL EXCEPTION;
    CARACTENER_INSUFICIENTE EXCEPTION;
    PRAGMA EXCEPTION_INIT(CONSTRASEÑA_ES_NULL,-20013);
    PRAGMA EXCEPTION_INIT(CARACTENER_INSUFICIENTE,-20014);
    ADMINISTRADOR_ES_NULL EXCEPTION;
    ADMINISTRADOR_INVALIDO EXCEPTION;
    PRAGMA EXCEPTION_INIT(ADMINISTRADOR_ES_NULL,-20016);
    PRAGMA EXCEPTION_INIT(ADMINISTRADOR_INVALIDO,-20017);
    NOMBRE_ES_NULL EXCEPTION;
    APELLIDO_ES_NULL EXCEPTION;
    PRAGMA EXCEPTION_INIT(NOMBRE_ES_NULL,-20019);
    PRAGMA EXCEPTION_INIT(APELLIDO_ES_NULL,-20020);
    FECHA_ES_NULL EXCEPTION;
    FECHA_FUTURA EXCEPTION;
    PRAGMA EXCEPTION_INIT(FECHA_ES_NULL,-20022);
    PRAGMA EXCEPTION_INIT(FECHA_FUTURA,-20023);
    TELEFONO_ES_NULL EXCEPTION;
    FUERA_RANGO EXCEPTION;
    PRAGMA EXCEPTION_INIT(TELEFONO_ES_NULL,-20025);
    PRAGMA EXCEPTION_INIT(FUERA_RANGO,-20026);
    COMUNA_ES_NULL EXCEPTION;
    CALLE_ES_NULL EXCEPTION;
    PRAGMA EXCEPTION_INIT(COMUNA_ES_NULL,-20028);
    PRAGMA EXCEPTION_INIT(CALLE_ES_NULL,-20029);
    CORREO_ES_NULL EXCEPTION;
    CORREO_REPETIDO EXCEPTION;
    PRAGMA EXCEPTION_INIT(CORREO_ES_NULL,-20031);
    PRAGMA EXCEPTION_INIT(CORREO_REPETIDO,-20032);
BEGIN 
    LOCK TABLE CLIENTE IN ROW EXCLUSIVE MODE;
    INSERT INTO CLIENTE VALUES(RUT_ENTRADA,CONTRASEÑA_ENTRADA,ADMINISTRADOR_ENTRADA,NOMBRE_COMPLETO(NOMBRE_ENTRADA,APELLIDO_ENTRADA),
    FECHA_ENTRADA,TELEFONO_ENTRADA,DIRECCION(COMUNA_ENTRADA,CALLE_ENTRADA,NUMERO_CASA_ENTRADA,NUMERO_DEPARTAMENTO_ENTRADA,BLOQUE_ENTRADA),CORREO_ENTRADA);
    COMMIT;
    MENSAJE := 'MIAU CLIENTE';
EXCEPTION
    WHEN RUT_ES_NULL THEN
        MENSAJE := 'EL RUT ES NULL';
        ROLLBACK;
    WHEN RUT_REPETIDO THEN
        MENSAJE :='ESE CLIENTE YA ESTA REGISTRADO';
        ROLLBACK;
    WHEN CONSTRASEÑA_ES_NULL THEN
        MENSAJE :='NO SE INGRESO UNA CONTRASEÑA';
        ROLLBACK;
    WHEN CARACTENER_INSUFICIENTE THEN
        MENSAJE :='LA CONTRASEÑA DEBE TENER ALEMNOS 8 CARACTERES';
        ROLLBACK;
    WHEN ADMINISTRADOR_ES_NULL THEN
        MENSAJE :='NO SE INGRESO EL TIPO DE USUARIO';
        ROLLBACK;
    WHEN ADMINISTRADOR_INVALIDO THEN
        MENSAJE :='SOLO SE PUEDE RESIVIR SI O NO';
        ROLLBACK;
    WHEN NOMBRE_ES_NULL THEN
        MENSAJE :='NO SE INGRESO UN NOMBRE';
        ROLLBACK;
    WHEN APELLIDO_ES_NULL THEN
        MENSAJE :='NO SE INGRESO EL APELLIDO';
        ROLLBACK;
    WHEN FECHA_ES_NULL THEN
        MENSAJE :='NO SE INGRESO LA FECHA DE NACIMIENTO';
        ROLLBACK;
    WHEN FECHA_FUTURA THEN
        MENSAJE :='SE INGRESO UNA FECHA INVALIDA';
        ROLLBACK;
    WHEN TELEFONO_ES_NULL THEN
        MENSAJE :='NO SE INGRESO UN TELEFONO';
        ROLLBACK;
    WHEN FUERA_RANGO THEN
        MENSAJE :='INGRESO UN TELEFONO INVALIDO';
        ROLLBACK;
    WHEN COMUNA_ES_NULL THEN
        MENSAJE :='NO SE INGRESO LA COMUNA';
        ROLLBACK;
    WHEN CALLE_ES_NULL THEN
        MENSAJE :='NO SE INGRESO LA CALLE';
        ROLLBACK;
    WHEN CORREO_ES_NULL THEN
        MENSAJE :='NO SE INGRESO UN CORREO';
        ROLLBACK;
    WHEN CORREO_REPETIDO THEN
        MENSAJE :='ESE CORREO YA FUE REGISTRADO';
        ROLLBACK;
    WHEN OTHERS THEN
        MENSAJE :='ERROR NO IDENTIFICADO EN CLIENTE';
        ROLLBACK;
END;

-- DESPACHO

CREATE OR REPLACE PROCEDURE INGRESAR_DESPACHO(
    RUT_REPA_ENTRADA IN DESPACHO.RUT_REPARTIDOR%TYPE,
    RUT_CLIE_ENTRADA IN DESPACHO.RUT_CLIENTE%TYPE,
    ESTADO_ENTRADA IN DESPACHO.ESTADO%TYPE,
    MENSAJE OUT VARCHAR
)
IS 
    RUT_ES_NULL_REPARTIDOR EXCEPTION;
    RUT_INEXISTENTE_REPARTIDOR EXCEPTION;
    PRAGMA EXCEPTION_INIT(RUT_ES_NULL_REPARTIDOR,-20040);
    PRAGMA EXCEPTION_INIT(RUT_INEXISTENTE_REPARTIDOR,-20041);
    RUT_ES_NULL_CLIENTE EXCEPTION;
    RUT_INEXISTENTE_CLIENTE EXCEPTION;
    PRAGMA EXCEPTION_INIT(RUT_ES_NULL_CLIENTE,-20043);
    PRAGMA EXCEPTION_INIT(RUT_INEXISTENTE_CLIENTE,-20044);  
    ESTADO_ES_NULL EXCEPTION;
    PRAGMA EXCEPTION_INIT(ESTADO_ES_NULL,-20046);
BEGIN
    LOCK TABLE DESPACHO IN ROW EXCLUSIVE MODE;
    INSERT INTO DESPACHO(RUT_REPARTIDOR,RUT_CLIENTE,ESTADO) VALUES(RUT_REPA_ENTRADA,RUT_CLIE_ENTRADA,ESTADO_ENTRADA);
    COMMIT;
    MENSAJE := 'MIAU DESPACHO';
EXCEPTION
    WHEN RUT_ES_NULL_REPARTIDOR THEN
        MENSAJE :='EL RUT ES NULL';
        ROLLBACK;
    WHEN RUT_INEXISTENTE_REPARTIDOR THEN
        MENSAJE :='EL REPARTIDOR NO ESTA REGISTRADO';
        ROLLBACK;
    WHEN RUT_ES_NULL_CLIENTE THEN
        MENSAJE :='EL RUT ES NULL';
        ROLLBACK;
    WHEN RUT_INEXISTENTE_CLIENTE THEN
        MENSAJE :='EL REPARTIDOR NO ESTA REGISTRADO';
        ROLLBACK;
    WHEN ESTADO_ES_NULL THEN
        MENSAJE :='EL ESTADO ES NULL';
        ROLLBACK;
    WHEN OTHERS THEN 
        MENSAJE :='ERROR NO IDENTIFICADO CON EL DESPACHO';
        ROLLBACK;
END;

-- CATEGORIA 

CREATE OR REPLACE PROCEDURE INGRESAR_CATEGORIA(
    NOMBRE_ENTRADA IN CATEGORIA.NOMBRE_CATEGORIA%TYPE,
    MENSAJE OUT VARCHAR
)
IS 
    NOMBRE_CATEGORIA_ES_NULL EXCEPTION;
    NOMBRE_USADO EXCEPTION;
    PRAGMA EXCEPTION_INIT(NOMBRE_CATEGORIA_ES_NULL,-20050);
    PRAGMA EXCEPTION_INIT(NOMBRE_USADO,-20051);
BEGIN 
    LOCK TABLE CATEGORIA IN ROW EXCLUSIVE MODE;
    INSERT INTO CATEGORIA(NOMBRE_CATEGORIA) VALUES(NOMBRE_ENTRADA);
    COMMIT;
    MENSAJE := 'MIAU CATEGORIA';
EXCEPTION
    WHEN NOMBRE_CATEGORIA_ES_NULL THEN
        MENSAJE :='NOMBRE DE CATEGORIA ES NULL';
        ROLLBACK;
    WHEN NOMBRE_USADO THEN
        MENSAJE :='ESE NOMBRE DE CATEGORIA YA ESTA EN USO';
        ROLLBACK;
    WHEN OTHERS THEN
        MENSAJE :='ERROR NO IDENTIFICADO EN CATEGORIA';
        ROLLBACK;
END;

-- PRODUCTO

CREATE OR REPLACE PROCEDURE INGRESAR_PRODUCTO(
    NOMBRE_ENTRADA IN PRODUCTO.NOMBRE%TYPE,
    PRECIO_ENTRADA IN PRODUCTO.PRECIO%TYPE,
    CODIGO_CATEGORIA_ENTRADA IN PRODUCTO.CODIGO_CATEGORIA%TYPE,
    RESTRINGIDO_ENTRADA IN PRODUCTO.RESTRINGIDO%TYPE,
    STOCK_ENTRADA IN PRODUCTO.STOCK%TYPE,
    MENSAJE OUT VARCHAR
)
IS 
    NOMBRE_PRODUCTO_ES_NULL EXCEPTION;
    NOMBRE_EN_USO EXCEPTION;
    PRAGMA EXCEPTION_INIT(NOMBRE_PRODUCTO_ES_NULL,-20060);
    PRAGMA EXCEPTION_INIT(NOMBRE_EN_USO,-20061);
    PRECIO_ES_NULL EXCEPTION;
    PRECIO_INVALIDO EXCEPTION;
    PRAGMA EXCEPTION_INIT(PRECIO_ES_NULL,-20063);
    PRAGMA EXCEPTION_INIT(PRECIO_INVALIDO,-20064);
    CATEGORIA_ES_NULL EXCEPTION;
    CATEGORIA_INEXISTENTE EXCEPTION;
    PRAGMA EXCEPTION_INIT(CATEGORIA_ES_NULL,-20066);
    PRAGMA EXCEPTION_INIT(CATEGORIA_INEXISTENTE,-20067);
    RESTRINGIDO_ES_NULL EXCEPTION;
    RESTRINGIDO_INVALIDO EXCEPTION;
    PRAGMA EXCEPTION_INIT(RESTRINGIDO_ES_NULL,-20069);
    PRAGMA EXCEPTION_INIT(RESTRINGIDO_INVALIDO,-20070);
    STOCK_ES_NULL EXCEPTION;
    STOCK_INVALIDO EXCEPTION;
    PRAGMA EXCEPTION_INIT(STOCK_ES_NULL,-20072);
    PRAGMA EXCEPTION_INIT(STOCK_INVALIDO,-20073);
BEGIN 
    LOCK TABLE PRODUCTO IN ROW EXCLUSIVE MODE;
    INSERT INTO PRODUCTO(NOMBRE,PRECIO,CODIGO_CATEGORIA,RESTRINGIDO,STOCK) VALUES (NOMBRE_ENTRADA,PRECIO_ENTRADA,CODIGO_CATEGORIA_ENTRADA,RESTRINGIDO_ENTRADA,STOCK_ENTRADA);
    COMMIT;
    MENSAJE := 'MIAU PRODUCTO';
EXCEPTION
    WHEN NOMBRE_PRODUCTO_ES_NULL THEN
        MENSAJE :='NO SE INGRESO EL NOMBRE DEL PRODUCTO';
        ROLLBACK;
    WHEN NOMBRE_EN_USO THEN
        MENSAJE :='ESE NOMBRE DE PRODUCTO YA ESTA EN USO';
        ROLLBACK;
    WHEN PRECIO_ES_NULL THEN
        MENSAJE :='NO SE INGRESO PRECIO DEL PRODUCTO';
        ROLLBACK;
    WHEN PRECIO_INVALIDO THEN
        MENSAJE :='NO SE PUEDE INGRESAR ESE PRECIO AL PRODUCTO';
        ROLLBACK;
    WHEN CATEGORIA_ES_NULL THEN
        MENSAJE :='NO SE INGRESO EL CODIGO DE CATEGORIA';
        ROLLBACK;
    WHEN CATEGORIA_INEXISTENTE THEN
        MENSAJE :='ESE CODIGO DE CATEGORIA NO EXISTE';
        ROLLBACK;
    WHEN RESTRINGIDO_ES_NULL  THEN
        MENSAJE :='NO SE INGRESO RESTRINGIDO';
        ROLLBACK;
    WHEN RESTRINGIDO_INVALIDO THEN
        MENSAJE :='RESTRINGIDO INVALIDO';
        ROLLBACK;
    WHEN STOCK_ES_NULL THEN
        MENSAJE :='NO SE INGRESO EL STOCK DEL PRODUCTO';
        ROLLBACK;
    WHEN STOCK_INVALIDO THEN
        MENSAJE :='NO SE PUEDE INGRESAR ESE STOCK';
        ROLLBACK;
    WHEN OTHERS THEN
        MENSAJE :='ERROR NO IDENTIFICADO EN PRODUCTO';
        ROLLBACK;
END;

-- BOLETA

CREATE OR REPLACE PROCEDURE INGRESAR_BOLETA(
    NOMBRE_PAGO_ENTRADA IN BOLETA.TIPO_PAGO.NOMBRE_PAGO%TYPE,
    NUMERO_TARJETA_ENTRADA IN BOLETA.TIPO_PAGO.NUMERO_TARJETA%TYPE,
    FECHA_EXPIRACION_ENTRADA  IN BOLETA.TIPO_PAGO.FECHA_EXPIRACION%TYPE,
    CVV_ENTRADA IN BOLETA.TIPO_PAGO.CVV%TYPE,
    MENSAJE OUT VARCHAR
)
IS 
    NOMBRE_PAGO_ES_NULL EXCEPTION;
    NUMERO_PAGO_ES_NULL EXCEPTION;
    FECHA_EXPIRACION_ES_NULL EXCEPTION;
    CVV_ES_NULL EXCEPTION;
    PRAGMA EXCEPTION_INIT(NOMBRE_PAGO_ES_NULL,-20080);
    PRAGMA EXCEPTION_INIT(NUMERO_PAGO_ES_NULL,-20081);
    PRAGMA EXCEPTION_INIT(FECHA_EXPIRACION_ES_NULL,-20082);
    PRAGMA EXCEPTION_INIT(CVV_ES_NULL,-20083);
    FECHA DATE;
BEGIN
    LOCK TABLE BOLETA IN ROW EXCLUSIVE MODE;
    FECHA := OBTENER_FECHA();
    INSERT INTO BOLETA(FECHA_BOLETA,TIPO_PAGO,TOTAL) VALUES(FECHA,PAGO(NOMBRE_PAGO_ENTRADA,NUMERO_TARJETA_ENTRADA,FECHA_EXPIRACION_ENTRADA,CVV_ENTRADA),0);
    COMMIT;
    MENSAJE := 'MIAU BOLETA';
EXCEPTION
    WHEN NOMBRE_PAGO_ES_NULL THEN
        MENSAJE :='NO SE INGRESO EL TIPO DE PAGO';
        ROLLBACK;
    WHEN NUMERO_PAGO_ES_NULL THEN
        MENSAJE :='NO SE INGRESO EL NUMERO DE LA TARJETA';
        ROLLBACK;
    WHEN FECHA_EXPIRACION_ES_NULL THEN
        MENSAJE :='NO SE INGRESO LA FECHA DE EXPIRACION DE LA TARJETA';
        ROLLBACK;
    WHEN CVV_ES_NULL THEN
        MENSAJE :='NO SE INGRESO EL CVV DE LA TARJETA';
        ROLLBACK;
    WHEN OTHERS THEN
        MENSAJE :='ERROR NO IDENTIFICADO EN BOLETA';
        ROLLBACK;
END;

-- DETALLE

CREATE OR REPLACE PROCEDURE INGRESAR_DETALLE(
    CODIGO_PRODUCTO_ENTRADA IN DETALLE.CODIGO_PRODUCTO%TYPE,
    CANTIDAD_ENTRADA IN DETALLE.CANTIDAD%TYPE,
    MENSAJE OUT VARCHAR
)
IS 
BEGIN
    LOCK TABLE DETALLE IN ROW EXCLUSIVE MODE;
    INSERT INTO DETALLE(CODIGO_PRODUCTO,CANTIDAD) VALUES (CODIGO_PRODUCTO_ENTRADA,CANTIDAD_ENTRADA);
    COMMIT;
    MENSAJE := 'MIAU DETALLE';
EXCEPTION
    WHEN OTHERS THEN
        MENSAJE :='ERROR NO IDENTIFICADO EN DETALLE';
        ROLLBACK;
END;

-- CARRO TEMPORAL

CREATE OR REPLACE PROCEDURE INGRESAR_CARRO_TEMPORAL(
    RUT_ENTRADA IN CARRO_TEMPORAL.RUT_CLIENTE%TYPE,
    CODIGO_ENTRADA IN CARRO_TEMPORAL.CODIGO_PRODUCTO%TYPE,
    CANTIDAD_ENTRADA IN CARRO_TEMPORAL.CANTIDAD%TYPE,
    MENSAJE OUT VARCHAR
)
IS
    CODIGO_PRODUCTO_ES_NULL EXCEPTION;
    CODIGO_PRODUCTO_INEXISTENTE EXCEPTION;
    CANTIDAD_ES_NULL EXCEPTION;
    CANTIDAD_INVALIDA EXCEPTION;
    MUCHA_DEMANDA EXCEPTION;
    PRAGMA EXCEPTION_INIT(CODIGO_PRODUCTO_ES_NULL,-20090);
    PRAGMA EXCEPTION_INIT(CODIGO_PRODUCTO_INEXISTENTE,-20091);
    PRAGMA EXCEPTION_INIT(CANTIDAD_ES_NULL,-20092);
    PRAGMA EXCEPTION_INIT(CANTIDAD_INVALIDA,-20093);
    PRAGMA EXCEPTION_INIT(MUCHA_DEMANDA,-20094);
    MENOR_DE_18 EXCEPTION;
    MENOR_DE_14 EXCEPTION;
    PRAGMA EXCEPTION_INIT(CANTIDAD_INVALIDA,-20096);
    PRAGMA EXCEPTION_INIT(MUCHA_DEMANDA,-20097);
BEGIN 
    LOCK TABLE CARRO_TEMPORAL IN ROW EXCLUSIVE MODE;
    INSERT INTO CARRO_TEMPORAL(RUT_CLIENTE,CODIGO_PRODUCTO,CANTIDAD) VALUES (RUT_ENTRADA,CODIGO_ENTRADA,CANTIDAD_ENTRADA);
    COMMIT;
    MENSAJE := 'MIAU TEMPORAL';
EXCEPTION
    WHEN CODIGO_PRODUCTO_ES_NULL THEN
        MENSAJE :='NO SE INGRESO EL CODIGO DE PRODUCTO';
        ROLLBACK;
    WHEN CODIGO_PRODUCTO_INEXISTENTE THEN
        MENSAJE :='ESE PRODUCTO NO ESTA REGISTRADO';
        ROLLBACK;
    WHEN CANTIDAD_ES_NULL THEN
        MENSAJE :='NO SE INGRESO LA CANTIDAD';
        ROLLBACK;
    WHEN CANTIDAD_INVALIDA THEN
        MENSAJE :='NO SE PUEDE PEDIR ESA CANTIDAD';
        ROLLBACK;
    WHEN MUCHA_DEMANDA THEN
        MENSAJE :='PIDIO MAS PRODUCTOS QUE EL STOCK DISPONIBLE';
        ROLLBACK;
    WHEN MENOR_DE_18 THEN
        MENSAJE :='DEBE TENER ALMENOS 18 AÑOS PARA COMPRAR ESTE PRODUCTO';
        ROLLBACK;
    WHEN MENOR_DE_14 THEN
        MENSAJE :='DEBE TENER ALMENOS 14 AÑOS PARA COMPRAR ESTE PRODUCTO';
        ROLLBACK;
    WHEN OTHERS THEN
        MENSAJE :='ERROR NO IDENTIFICADO EN DETALLE';
        ROLLBACK;
END;

-- 

CREATE OR REPLACE PROCEDURE INGRESAR_CARRO(
    RUT_CLIENTE_ENTRADA IN CLIENTE.RUT%TYPE,
    RUT_REPARTIDOR_ENTRADA IN REPARTIDOR.RUT%TYPE,
    ESTADO_ENTRADA IN DESPACHO.ESTADO%TYPE,
    NOMBRE_PAGO_ENTRADA IN BOLETA.TIPO_PAGO.NOMBRE_PAGO%TYPE,
    NUMERO_TARJETA_ENTRADA IN BOLETA.TIPO_PAGO.NUMERO_TARJETA%TYPE,
    FECHA_EXPIRACION_ENTRADA  IN BOLETA.TIPO_PAGO.FECHA_EXPIRACION%TYPE,
    CVV_ENTRADA IN BOLETA.TIPO_PAGO.CVV%TYPE,
    MENSAJE OUT VARCHAR
)
IS 
    CURSOR FILAS_PRO IS SELECT CODIGO_PRODUCTO FROM CARRO_TEMPORAL WHERE RUT_CLIENTE = RUT_CLIENTE_ENTRADA;
    UNA_FILA_PRO NUMBER;
    CURSOR FILAS_CANTIDAD IS SELECT CANTIDAD FROM CARRO_TEMPORAL WHERE RUT_CLIENTE = RUT_CLIENTE_ENTRADA;
    UNA_FILA_CANTIDAD NUMBER;
    ERROR_CARRO_TEMPORAL EXCEPTION;
    NO_EXISTE_CARRO EXCEPTION;
    ERROR_CARRO EXCEPTION;
    STOCK_REAL NUMBER;
    I NUMBER;
    CANTIDAD_DETALLE NUMBER;
    MAXIMO_COD NUMBER;
    COD_PRO_ACTUAL NUMBER;
    CANTIDAD_ACTUAL NUMBER;
    MAX_BOLETA_VIEJO NUMBER;
    MAX_BOLETA_NUEVO NUMBER;

BEGIN
    LOCK TABLE CARRO_TEMPORAL IN ROW EXCLUSIVE MODE;
    SELECT MAX(CODIGO_BOLETA) INTO MAX_BOLETA_VIEJO FROM BOLETA;
    OPEN FILAS_PRO;
    OPEN FILAS_CANTIDAD;
    FETCH FILAS_PRO INTO UNA_FILA_PRO;
    FETCH FILAS_CANTIDAD INTO UNA_FILA_CANTIDAD;
    WHILE FILAS_PRO%FOUND LOOP
        SELECT STOCK INTO STOCK_REAL FROM PRODUCTO WHERE CODIGO_PRODUCTO = UNA_FILA_PRO;
        IF UNA_FILA_CANTIDAD > STOCK_REAL THEN
            CLOSE FILAS_PRO;
            CLOSE FILAS_CANTIDAD;
            --DBMS_OUTPUT.PUT_LINE('SE PIDIERON '||UNA_FILA_CANTIDAD||' PERO SOLO HAY '||STOCK_REAL||' DEL PROCUCTO '||UNA_FILA_PRO);
            RAISE ERROR_CARRO_TEMPORAL;
        END IF;
        FETCH FILAS_PRO INTO UNA_FILA_PRO;
        FETCH FILAS_CANTIDAD INTO UNA_FILA_CANTIDAD;
    END LOOP;
    CLOSE FILAS_PRO;
    CLOSE FILAS_CANTIDAD;
    SELECT COUNT(*) INTO CANTIDAD_DETALLE FROM CARRO_TEMPORAL WHERE RUT_CLIENTE = RUT_CLIENTE_ENTRADA;
    IF CANTIDAD_DETALLE >= 1 THEN
        --DBMS_OUTPUT.PUT_LINE('LLAMAR');
        INGRESAR_DESPACHO(RUT_REPARTIDOR_ENTRADA, RUT_CLIENTE_ENTRADA, ESTADO_ENTRADA,MENSAJE);
        --DBMS_OUTPUT.PUT_LINE('DESPACHO CREADO');
        INGRESAR_BOLETA(NOMBRE_PAGO_ENTRADA,NUMERO_TARJETA_ENTRADA, FECHA_EXPIRACION_ENTRADA, CVV_ENTRADA,MENSAJE);
        --DBMS_OUTPUT.PUT_LINE('BOLETA CREADA');
        I := 0;
        WHILE I <  CANTIDAD_DETALLE LOOP
            SELECT MAX(CODIGO_CARRO) INTO MAXIMO_COD FROM CARRO_TEMPORAL WHERE RUT_CLIENTE = RUT_CLIENTE_ENTRADA;
            SELECT CODIGO_PRODUCTO INTO COD_PRO_ACTUAL FROM CARRO_TEMPORAL WHERE CODIGO_CARRO = MAXIMO_COD;
            SELECT CANTIDAD INTO CANTIDAD_ACTUAL FROM CARRO_TEMPORAL WHERE CODIGO_CARRO = MAXIMO_COD;
            INGRESAR_DETALLE(COD_PRO_ACTUAL,CANTIDAD_ACTUAL,MENSAJE);
            --DBMS_OUTPUT.PUT_LINE('DETELLE : '||I||' INGRESADO');
            DELETE FROM CARRO_TEMPORAL WHERE CODIGO_CARRO = MAXIMO_COD;
            I := I + 1;
        END LOOP;
        SELECT MAX(CODIGO_BOLETA) INTO MAX_BOLETA_NUEVO FROM BOLETA;
        IF MAX_BOLETA_VIEJO = MAX_BOLETA_NUEVO THEN
            RAISE ERROR_CARRO;
        ELSE
            DELETE FROM CARRO_TEMPORAL WHERE RUT_CLIENTE = RUT_CLIENTE_ENTRADA;
            COMMIT;
            MENSAJE := 'MIAU COMPRA';
        END IF;
    ELSE
        RAISE NO_EXISTE_CARRO;
    END IF;
    
EXCEPTION   
    WHEN ERROR_CARRO_TEMPORAL THEN
        MENSAJE :='DEBE REGRESAR';
        ROLLBACK;
    WHEN NO_EXISTE_CARRO THEN
        MENSAJE :='DEBE REGRESAR';
        ROLLBACK;
    WHEN ERROR_CARRO THEN
        MENSAJE :='NO IDENTIFICADO EL CREAR CARRO';
        ROLLBACK;
    WHEN OTHERS THEN
        MENSAJE :='ERROR NO CAPTURADO EN HACER EL CARRO';
        ROLLBACK;
END;


-- TU CULPA

CREATE OR REPLACE PROCEDURE CREAR_BASE
IS 
    MENSAJE VARCHAR(20);
BEGIN
    INGRESAR_REPARTIDOR(18876123, 'MIS', 'VIEJO',MENSAJE);
    INGRESAR_REPARTIDOR(20199732,'RICARDO', 'VERGARA',MENSAJE);
    INGRESAR_REPARTIDOR(20306648,'TEFA', 'BEBE',MENSAJE); 
    INGRESAR_REPARTIDOR(20306677,'La' ,'MICHI',MENSAJE); 
    INGRESAR_REPARTIDOR(20000000, 'CERO', 'CERO',MENSAJE);

    INGRESAR_CLIENTE(20305990,'contraseña','NO','LEVI','URBINA',TO_DATE ('12-12-2000','DD-MM-YY'),90000000,'TALCA','CERCA U', 2031, NULL, NULL, 'leviurbina@gmail.com',MENSAJE);
    INGRESAR_CLIENTE(20306648,'michi michi','Si','TEFA','ALARCON',TO_DATE ('29-02-2000','DD-MM-YY'),90000001,'TALCA','CERCA MALL', 2044, NULL, NULL, 'tefachica@gmail.com',MENSAJE);
    INGRESAR_CLIENTE(21000000,'101010101010101','si' ,'DIEZ' , 'EL', TO_DATE ('10-10-2010','DD-MM-YY') ,90000002, 'TALCA' , 'FRENTE A LA U', 1456, NULL, NULL, 'elcorreo@gmail.com',MENSAJE);

    INGRESAR_CATEGORIA('CONGELADOS',MENSAJE);
    INGRESAR_CATEGORIA('ASEO',MENSAJE);
    INGRESAR_CATEGORIA('INSUMOS',MENSAJE);
    INGRESAR_CATEGORIA('PANADERIA',MENSAJE);
    INGRESAR_CATEGORIA('DULCES',MENSAJE);


    INGRESAR_PRODUCTO('HELADO DE CHOCOLATE 1L.',3200,1,'NO',10,MENSAJE);
    INGRESAR_PRODUCTO('EMPANADAS DE QUESO DOCENA',6000,1,'SI',5,MENSAJE);
    INGRESAR_PRODUCTO('LAVA LOZAS 500ML.',2000,2,'NO',10,MENSAJE);
    INGRESAR_PRODUCTO('CONFORT 8 UNI.50MTS.',8000,2,'NO',15,MENSAJE);
    INGRESAR_PRODUCTO('PAPAS LAYS DE QUESO 134GR,',2000,3,'NO',10,MENSAJE);
    INGRESAR_PRODUCTO('MANï¿½ SIN SAL 180GR.',1000,3,'NO',10,MENSAJE);
    INGRESAR_PRODUCTO('MARRAQUETA KG.',1500,4,'NO',6,MENSAJE);
    INGRESAR_PRODUCTO('DOBLADITAS KG.',2000,4,'NO',6,MENSAJE);
    INGRESAR_PRODUCTO('GOMITAS FLYPI',800,5,'NO',40,MENSAJE);
    INGRESAR_PRODUCTO('PAPAS DUQUESA', 1200, 1, 'NO',12,MENSAJE);

    INGRESAR_CARRO_TEMPORAL(20305990, 1,2,MENSAJE);
    INGRESAR_CARRO_TEMPORAL(20305990, 2,3,MENSAJE);
    INGRESAR_CARRO_TEMPORAL(20305990, 10,2,MENSAJE);
    
    INGRESAR_CARRO(20305990,20199732,'PELEA', 'DEBITO',201567645,TO_DATE ('30-12-2030','DD-MM-YY'), NULL,MENSAJE);

    INGRESAR_CARRO_TEMPORAL(20306648, 2,2,MENSAJE);
    INGRESAR_CARRO_TEMPORAL(20306648, 10,2,MENSAJE);

    INGRESAR_CARRO(20306648,20306677,'MIAU', 'DEBITO',201567667,TO_DATE ('30-12-2030','DD-MM-YY'), NULL,MENSAJE);
END;


