
-------/\/\     /\/\
--UwU (/Ã¯Â¿Â½vÃ¯Â¿Â½)/ \(Ã¯Â¿Â½vÃ¯Â¿Â½\)
------(    )   (    )
--     v--v     v--v


DROP TABLE CARRO_TEMPORAL;
DROP TABLE DETALLE;
DROP TABLE BOLETA;
DROP TABLE DESPACHO;
DROP TABLE PRODUCTO;
DROP TABLE CATEGORIA;
DROP TABLE REPARTIDOR;
DROP TABLE CLIENTE;


CREATE OR REPLACE TYPE NOMBRE_COMPLETO AS OBJECT(
    NOMBRE VARCHAR2(20),
    APELLIDO VARCHAR2(20)
);

CREATE OR REPLACE TYPE DIRECCION AS OBJECT(
    COMUNA VARCHAR2(50),
    CALLE VARCHAR2(50),
    NUMERO_CASA NUMBER,
    NUMERO_DEPARTAMENTO NUMBER,
    BLOQUE NUMBER
);

CREATE TABLE CLIENTE(
    RUT NUMBER NOT NULL,
    CONTRASEÑA VARCHAR(30) NOT NULL,
    ADMINISTRADOR VARCHAR(2),
    NOMBRE_CLIENTE NOMBRE_COMPLETO,
    FECHA_NACIMIENTO DATE,
    TELEFONO NUMBER,
    DIRECCION_CLIENTE DIRECCION,
    CORREO VARCHAR(50)
);

CREATE TABLE REPARTIDOR(
    RUT NUMBER NOT NULL,
    NOMBRE_REPARTIDOR NOMBRE_COMPLETO
);

CREATE TABLE DESPACHO(
    CODIGO_SEGUIMIENTO NUMBER NOT NULL,
    RUT_REPARTIDOR NUMBER NOT NULL,
    RUT_CLIENTE NUMBER NOT NULL,
    TIEMPO_ENTREGA NUMBER,
    ESTADO VARCHAR(50),
    COSTO_DESPACHO NUMBER
);

CREATE TABLE CATEGORIA(
    CODIGO_CATEGORIA NUMBER NOT NULL,
    NOMBRE_CATEGORIA VARCHAR(20)
);

CREATE TABLE PRODUCTO(
    CODIGO_PRODUCTO NUMBER NOT NULL,
    NOMBRE VARCHAR2(30),
    PRECIO NUMBER,
    CODIGO_CATEGORIA NUMBER,
    RESTRINGIDO VARCHAR(2),
    STOCK NUMBER
);

CREATE OR REPLACE TYPE PAGO AS OBJECT(
    NOMBRE_PAGO VARCHAR(50),
    NUMERO_TARJETA NUMBER,
    FECHA_EXPIRACION DATE,
    CVV NUMBER
);

CREATE TABLE BOLETA(
    CODIGO_BOLETA NUMBER NOT NULL,
    CODIGO_SEGUIMIENTO NUMBER NOT NULL,
    FECHA_BOLETA DATE,
    TIPO_PAGO PAGO,
    TOTAL NUMBER
);

CREATE TABLE DETALLE(
    CODIGO_BOLETA NUMBER NOT NULL,
    CODIGO_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER,
    TOTAL NUMBER
);

CREATE TABLE CARRO_TEMPORAL(
    CODIGO_CARRO NUMBER NOT NULL,
    RUT_CLIENTE NUMBER NOT NULL,
    CODIGO_PRODUCTO NUMBER  NOT NULL,
    CANTIDAD NUMBER,
    TOTAL NUMBER
);

ALTER TABLE REPARTIDOR ADD CONSTRAINT PK_REPARTIDOR PRIMARY KEY(RUT);
ALTER TABLE DESPACHO ADD CONSTRAINT PK_DESPACHO PRIMARY KEY(CODIGO_SEGUIMIENTO);
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(RUT);
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY(CODIGO_CATEGORIA);
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTOS PRIMARY KEY(CODIGO_PRODUCTO);
ALTER TABLE BOLETA ADD CONSTRAINT PK_BOLETA PRIMARY KEY(CODIGO_BOLETA);
ALTER TABLE DETALLE ADD CONSTRAINT PK_DETALLE PRIMARY KEY(CODIGO_BOLETA,CODIGO_PRODUCTO);
ALTER TABLE CARRO_TEMPORAL ADD  CONSTRAINT PK_CARRO_TEMPORAL PRIMARY KEY(CODIGO_CARRO);

ALTER TABLE DESPACHO ADD CONSTRAINT FK_DESPACHO_REPARTIDOR FOREIGN KEY(RUT_REPARTIDOR) REFERENCES REPARTIDOR(RUT);
ALTER TABLE DESPACHO ADD CONSTRAINT FK_DESPACHO_CLIENTE FOREIGN KEY(RUT_CLIENTE) REFERENCES CLIENTE(RUT);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY(CODIGO_CATEGORIA) REFERENCES CATEGORIA(CODIGO_CATEGORIA);
ALTER TABLE BOLETA ADD CONSTRAINT FK_BOLETA FOREIGN KEY(CODIGO_SEGUIMIENTO) REFERENCES DESPACHO(CODIGO_SEGUIMIENTO);
ALTER TABLE DETALLE ADD CONSTRAINT FK_DETALLE_BOLETA FOREIGN KEY(CODIGO_BOLETA) REFERENCES BOLETA(CODIGO_BOLETA);
ALTER TABLE DETALLE ADD CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY(CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO);
ALTER TABLE CARRO_TEMPORAL ADD CONSTRAINT FK_CARRO_CLIENTE FOREIGN KEY(RUT_CLIENTE) REFERENCES CLIENTE(RUT);
ALTER TABLE CARRO_TEMPORAL ADD CONSTRAINT FK_CARRO_PRODCUTO FOREIGN KEY(CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO);

-- TRIGGERS

-- REPARTIDOR

CREATE OR REPLACE TRIGGER MINUSCULAS_REPARTIDOR
BEFORE INSERT ON REPARTIDOR FOR EACH ROW 
DECLARE 
BEGIN 
    :NEW.NOMBRE_REPARTIDOR.NOMBRE := LOWER(:NEW.NOMBRE_REPARTIDOR.NOMBRE);
    :NEW.NOMBRE_REPARTIDOR.APELLIDO := LOWER(:NEW.NOMBRE_REPARTIDOR.APELLIDO);
END;

CREATE OR REPLACE TRIGGER ERRORES_RUT_REPARTIDOR
BEFORE INSERT ON REPARTIDOR FOR EACH ROW 
DECLARE
    RUT_ES_NULL EXCEPTION;
    RUT_REPETIDO EXCEPTION;
    REPETICION NUMBER;
BEGIN
    IF :NEW.RUT IS NULL THEN
        RAISE RUT_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICION FROM REPARTIDOR WHERE RUT = :NEW.RUT;
        IF REPETICION = 1 THEN
            RAISE RUT_REPETIDO;
        END IF;
    END IF;

EXCEPTION
    WHEN RUT_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20001,'EL RUT ES NULL');
    WHEN RUT_REPETIDO THEN
        RAISE_APPLICATION_ERROR(-20002,'EL REPARTIDOR YA ESTA REGISTRADO');
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20003,'ERROR NO IDENTIFICADO EN EL NOMBRE');
END;

CREATE OR REPLACE TRIGGER ERRORES_NOMBRE_REPARTIDOR
BEFORE INSERT ON REPARTIDOR FOR EACH ROW 
DECLARE 
    NOMBRE_ES_NULL EXCEPTION;
    APELLIDO_ES_NULL EXCEPTION;
BEGIN 
    IF :NEW.NOMBRE_REPARTIDOR.NOMBRE IS NULL OR :NEW.NOMBRE_REPARTIDOR.APELLIDO IS NULL THEN 
        IF :NEW.NOMBRE_REPARTIDOR.NOMBRE IS NULL THEN 
            RAISE NOMBRE_ES_NULL;
        ELSE
            RAISE APELLIDO_ES_NULL;
        END IF;
    END IF;

EXCEPTION
    WHEN NOMBRE_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20004,'EL NOMBRE ES NULL');
    WHEN APELLIDO_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20005,'EL APELLIDO ES NULL');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20003,'ERROR NO IDENTIFICADO');
END;

-- CLIENTE

CREATE OR REPLACE TRIGGER MINUSCULAS_CLIENTE
BEFORE INSERT ON CLIENTE FOR EACH ROW 
DECLARE 
BEGIN 
    :NEW.NOMBRE_CLIENTE.NOMBRE := LOWER(:NEW.NOMBRE_CLIENTE.NOMBRE);
    :NEW.NOMBRE_CLIENTE.APELLIDO := LOWER(:NEW.NOMBRE_CLIENTE.APELLIDO);
    :NEW.DIRECCION_CLIENTE.COMUNA := LOWER(:NEW.DIRECCION_CLIENTE.COMUNA);
    :NEW.DIRECCION_CLIENTE.CALLE := LOWER(:NEW.DIRECCION_CLIENTE.CALLE);
    :NEW.ADMINISTRADOR := LOWER(:NEW.ADMINISTRADOR);
END;

CREATE OR REPLACE TRIGGER ERRORES_RUT_CLIENTE
BEFORE INSERT ON CLIENTE FOR EACH ROW 
DECLARE 
    RUT_ES_NULL EXCEPTION;
    RUT_REPETIDO EXCEPTION;
    REPETICION NUMBER;
BEGIN 
    IF :NEW.RUT IS NULL THEN
        RAISE RUT_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICION FROM CLIENTE WHERE RUT = :NEW.RUT;
        IF REPETICION = 1 THEN
            RAISE RUT_REPETIDO;
        END IF;
    END IF;
EXCEPTION
    WHEN RUT_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20010,'EL RUT ES NULL');
    WHEN RUT_REPETIDO THEN
        RAISE_APPLICATION_ERROR(-20011,'EL CLIENTE YA ESTA REGISTRADO');
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20012,'ERROR NO IDENTIFICADO EN EL RUT CLIENTE');
END;

CREATE OR REPLACE TRIGGER ERRORES_CONTRASEÑA
BEFORE INSERT ON CLIENTE FOR EACH ROW 
DECLARE
    CONSTRASEÑA_ES_NULL EXCEPTION;
    CARACTENER_INSUFICIENTE EXCEPTION;
    CANTIDAD_CARACTERES NUMBER;
BEGIN
    IF :NEW.CONTRASEÑA IS NULL THEN
        RAISE CONSTRASEÑA_ES_NULL;
    ELSE
        SELECT LENGTH(:NEW.CONTRASEÑA) INTO CANTIDAD_CARACTERES FROM DUAL;
        IF CANTIDAD_CARACTERES < 8 THEN
            RAISE CARACTENER_INSUFICIENTE;
        END IF;
    END IF;
EXCEPTION
    WHEN CONSTRASEÑA_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20013,'NO SE INGRESO UNA CONTRASEÑA');
    WHEN CARACTENER_INSUFICIENTE THEN
        RAISE_APPLICATION_ERROR(-20014,'LA CONTRASEÑA DEBE TENER ALEMNOS 8 CARACTERES');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20015,'ERROR NO CAPTURADO EN CONTRASEÑA');
END;

CREATE OR REPLACE TRIGGER ERRORES_ADMINISTRADOR
BEFORE INSERT ON CLIENTE FOR EACH ROW 
DECLARE 
    ADMINISTRADOR_ES_NULL EXCEPTION;
    ADMINISTRADOR_INVALIDO EXCEPTION;
BEGIN
    IF :NEW.ADMINISTRADOR IS NULL THEN
        RAISE ADMINISTRADOR_ES_NULL;
    ELSE
        :NEW.ADMINISTRADOR := LOWER(:NEW.ADMINISTRADOR);
        
        IF :NEW.ADMINISTRADOR = 'si' OR :NEW.ADMINISTRADOR = 'no' THEN 
           DBMS_OUTPUT.PUT_LINE('');
        ELSE
            RAISE ADMINISTRADOR_INVALIDO;
        END IF;
    END IF;
EXCEPTION
    WHEN ADMINISTRADOR_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20016,'NO SE INGRESO EL TIPO DE USUARIO');
    WHEN ADMINISTRADOR_INVALIDO THEN
        RAISE_APPLICATION_ERROR(-20017,'SOLO SE PUEDE RESIVIR SI O NO');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20018,'ERROR NO CAPUERADO EN TIPO DE ADMINISTRADOR');
END;

CREATE OR REPLACE TRIGGER ERRORES_NOMBRE_CLIENTE
BEFORE INSERT ON CLIENTE FOR EACH ROW 
DECLARE 
    NOMBRE_ES_NULL EXCEPTION;
    APELLIDO_ES_NULL EXCEPTION;
BEGIN
    IF :NEW.NOMBRE_CLIENTE.NOMBRE IS NULL OR :NEW.NOMBRE_CLIENTE.APELLIDO IS NULL THEN 
        IF :NEW.NOMBRE_CLIENTE.NOMBRE IS NULL THEN 
            RAISE NOMBRE_ES_NULL;
        ELSE
            RAISE APELLIDO_ES_NULL;
        END IF;
    END IF;
EXCEPTION
    WHEN NOMBRE_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-200019,'EL NOMBRE ES NULL');
    WHEN APELLIDO_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-200020,'EL APELLIDO ES NULL');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-200021,'ERROR NO IDENTIFICADO NOMBRE CLIENTE');
END;

CREATE OR REPLACE TRIGGER ERRORES_FECHA_NACIMIENTO
BEFORE INSERT ON CLIENTE FOR EACH ROW 
DECLARE 
    FECHA_ES_NULL EXCEPTION;
    FECHA_FUTURA EXCEPTION;
    FECHA_ACTUAL DATE;
BEGIN
    IF :NEW.FECHA_NACIMIENTO IS NULL THEN
        RAISE FECHA_ES_NULL;
    ELSE
        FECHA_ACTUAL := OBTENER_FECHA();
        IF :NEW.FECHA_NACIMIENTO > FECHA_ACTUAL THEN
            RAISE FECHA_FUTURA;
        END IF;
    END IF;
EXCEPTION 
    WHEN FECHA_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20022,'LA FECHA ES NULL');
    WHEN FECHA_FUTURA THEN 
        RAISE_APPLICATION_ERROR(-20023,'SE REGISTRO UNA FECHA FUTURA');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20024,'ERROR NO IDENTIFICADO EN FECHA NACIMIENTO');
END;

CREATE OR REPLACE TRIGGER ERRORES_TELEFONO
BEFORE INSERT ON CLIENTE FOR EACH ROW 
DECLARE 
    TELEFONO_ES_NULL EXCEPTION;
    FUERA_RANGO EXCEPTION;
BEGIN 
    IF :NEW.TELEFONO IS NULL THEN
        RAISE TELEFONO_ES_NULL;
    ELSE
        IF :NEW.TELEFONO < 1000000 THEN
            RAISE FUERA_RANGO;
        END IF;
    END IF;
EXCEPTION
    WHEN TELEFONO_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20025,'NO SE INGRESO NINGUN TELEFONO');
    WHEN FUERA_RANGO THEN
        RAISE_APPLICATION_ERROR(-20026,'TELEFONO INVALIDO');
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20027,'ERROR NO IDENTIFICADO EN TELEFONOS');
END;

CREATE OR REPLACE TRIGGER ERRORES_DIRECCION
BEFORE INSERT ON CLIENTE FOR EACH ROW 
DECLARE 
    COMUNA_ES_NULL EXCEPTION;
    CALLE_ES_NULL EXCEPTION;
BEGIN
    IF :NEW.DIRECCION_CLIENTE.COMUNA IS NULL OR :NEW.DIRECCION_CLIENTE.CALLE IS NULL THEN
        IF :NEW.DIRECCION_CLIENTE.COMUNA IS NULL THEN 
            RAISE COMUNA_ES_NULL;
        ELSE
            RAISE CALLE_ES_NULL;
        END IF;
    END IF;

EXCEPTION
    WHEN COMUNA_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20028,'NO SE INGRESO LA COMUNA');
    WHEN CALLE_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20029,'NO SE INGRESO LA CALLE');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20030,'ERROR NO IDENTIFICADO CON LA DIRECCION');
END;

CREATE OR REPLACE TRIGGER ERRORES_CORREO
BEFORE INSERT ON CLIENTE FOR EACH ROW 
DECLARE
    CORREO_ES_NULL EXCEPTION;
    CORREO_REPETIDO EXCEPTION;
    REPETICION NUMBER;
BEGIN
    IF :NEW.CORREO IS NULL THEN
        RAISE CORREO_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICION FROM CLIENTE WHERE CORREO = :NEW.CORREO;
        IF REPETICION = 1 THEN
            RAISE CORREO_REPETIDO;
        END IF;
    END IF;

EXCEPTION
    WHEN CORREO_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20031,'CORREO ES NULL');
    WHEN CORREO_REPETIDO THEN
        RAISE_APPLICATION_ERROR(-20032,'CORREO YA FUE REGISTRADO');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20033,'EROOR NO IDENTIFICADO EN CORERO');
END;

-- DESPACHO

CREATE OR REPLACE TRIGGER CODIGO_DESPACHO_AUTOMATICO
BEFORE INSERT ON DESPACHO FOR EACH ROW 
DECLARE 
    NUEVO_CODIGO NUMBER;
BEGIN 
    SELECT NVL(MAX(CODIGO_SEGUIMIENTO)+1,1) INTO NUEVO_CODIGO FROM DESPACHO;
    :NEW.CODIGO_SEGUIMIENTO := NUEVO_CODIGO;
END;

CREATE OR REPLACE TRIGGER MINUSCULAS_DESPACHO
BEFORE INSERT ON DESPACHO FOR EACH ROW 
DECLARE 
BEGIN 
    :NEW.ESTADO := LOWER(:NEW.ESTADO); 
END;

CREATE OR REPLACE TRIGGER Z_ACTUALIZAR_TIEMPO_COSTO
BEFORE INSERT ON DESPACHO FOR EACH ROW 
DECLARE 
    NUEVO_TIEMPO NUMBER;
    NUEVO_COSTO NUMBER;
BEGIN
    NUEVO_TIEMPO := 20;
    NUEVO_COSTO := 8000;
    :NEW.TIEMPO_ENTREGA := NUEVO_TIEMPO;
    :NEW.COSTO_DESPACHO := NUEVO_COSTO;
END;

CREATE OR REPLACE TRIGGER ERRORES_RUT_REPAR_DESPACHO
BEFORE INSERT ON DESPACHO FOR EACH ROW 
DECLARE 
    RUT_ES_NULL_REPARTIDOR EXCEPTION;
    RUT_INEXISTENTE_REPARTIDOR EXCEPTION;
    REPETICION NUMBER;
BEGIN 
    IF :NEW.RUT_REPARTIDOR IS NULL THEN
        RAISE RUT_ES_NULL_REPARTIDOR;
    ELSE
        SELECT COUNT(*) INTO REPETICION FROM REPARTIDOR WHERE RUT = :NEW.RUT_REPARTIDOR;
        IF REPETICION = 0 THEN
            RAISE RUT_INEXISTENTE_REPARTIDOR;
        END IF;
    END IF;

EXCEPTION
    WHEN RUT_ES_NULL_REPARTIDOR THEN
        DBMS_OUTPUT.PUT_LINE('EL RUT ES NULL');
        RAISE_APPLICATION_ERROR(-20040,'EL RUT ES NULL');
    WHEN RUT_INEXISTENTE_REPARTIDOR THEN
        DBMS_OUTPUT.PUT_LINE('EL REPARTIDOR NO ESTA INGRESADO');
        RAISE_APPLICATION_ERROR(-20041,'EL REPARTIDOR NO ESTA INGRESADO');
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO EN RUT DE REPARTIDOR');
        RAISE_APPLICATION_ERROR(-20042,'ERROR NO IDENTIFICADO RUT DE REPATIDRO');
END;

CREATE OR REPLACE TRIGGER ERRORES_RUT_CLIENTE_DESPACHO
BEFORE INSERT ON DESPACHO FOR EACH ROW 
DECLARE 
    RUT_ES_NULL_CLIENTE EXCEPTION;
    RUT_INEXISTENTE_CLIENTE EXCEPTION;
    REPETICION NUMBER;
BEGIN 
    IF :NEW.RUT_CLIENTE IS NULL THEN
        RAISE RUT_ES_NULL_CLIENTE;
    ELSE
        SELECT COUNT(*) INTO REPETICION FROM CLIENTE WHERE RUT = :NEW.RUT_CLIENTE;
        IF REPETICION = 0 THEN
            RAISE RUT_INEXISTENTE_CLIENTE;
        END IF;
    END IF;

EXCEPTION
    WHEN RUT_ES_NULL_CLIENTE THEN
        DBMS_OUTPUT.PUT_LINE('EL RUT ES NULL');
        RAISE_APPLICATION_ERROR(-20033,'EL RUT ES NULL');
    WHEN RUT_INEXISTENTE_CLIENTE THEN
        DBMS_OUTPUT.PUT_LINE('EL CLIENTE NO ESTA REGISTRADO');
        RAISE_APPLICATION_ERROR(-20034,'EL CLIENTE NO ESTA INGRESADO');
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO RUT CLIETNE DE DESPACHO');
        RAISE_APPLICATION_ERROR(-20035,'ERROR NO IDENTIFICADO RUT CLIENTE DE DESPACHO');
END;
    
CREATE OR REPLACE TRIGGER ERRORES_ESTADO_DESPACHO
BEFORE INSERT ON DESPACHO FOR EACH ROW 
DECLARE 
    ESTADO_ES_NULL EXCEPTION;
BEGIN 
    IF :NEW.ESTADO IS NULL THEN
        RAISE ESTADO_ES_NULL;
    END IF;

EXCEPTION
    WHEN ESTADO_ES_NULL THEN
        DBMS_OUTPUT.PUT_LINE('ESTADO ES NULL');
        RAISE_APPLICATION_ERROR(-20046,'ESTADO ES NULL');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO ESTADO');
        RAISE_APPLICATION_ERROR(-20047,'ERROR NO IDENTIFICADO ESTADO');
END;

-- CATEGORIA

CREATE OR REPLACE TRIGGER CODIGO_CATEGORIA_AUTOMATICO
BEFORE INSERT ON CATEGORIA FOR EACH ROW 
DECLARE 
    NUEVO_CODIGO NUMBER;
BEGIN 
    SELECT NVL(MAX(CODIGO_CATEGORIA)+1,1) INTO NUEVO_CODIGO FROM CATEGORIA;
    :NEW.CODIGO_CATEGORIA := NUEVO_CODIGO;
END;

CREATE OR REPLACE TRIGGER MINUSCULAS_CATEGORIA
BEFORE INSERT ON CATEGORIA FOR EACH ROW 
DECLARE 
BEGIN 
    :NEW.NOMBRE_CATEGORIA := LOWER(:NEW.NOMBRE_CATEGORIA); 
END;

CREATE OR REPLACE TRIGGER ERRORES_NOMBRE_CATEGORIA
BEFORE INSERT ON CATEGORIA FOR EACH ROW 
DECLARE
    NOMBRE_CATEGORIA_ES_NULL EXCEPTION;
    NOMBRE_USADO EXCEPTION;
    REPETICION NUMBER;
BEGIN
    IF :NEW.NOMBRE_CATEGORIA IS NULL THEN
        RAISE NOMBRE_CATEGORIA_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICION FROM CATEGORIA WHERE NOMBRE_CATEGORIA = LOWER(:NEW.NOMBRE_CATEGORIA);
        IF REPETICION = 1 THEN
            RAISE NOMBRE_USADO;
        END IF;
    END IF;
EXCEPTION
    WHEN NOMBRE_CATEGORIA_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20050,'NOMBRE ES NULL');
    WHEN NOMBRE_USADO THEN
        RAISE_APPLICATION_ERROR(-20051,'ESA CATEGORIA YA FUE REGISTRADA');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20052,'ERROR NO IDENTIFICADO EN NOMBRE CATEGORIA');
END;

-- PRODUCTO

CREATE OR REPLACE TRIGGER CODIGO_PRODUCTO_AUTOMATICO
BEFORE INSERT ON PRODUCTO FOR EACH ROW 
DECLARE 
    NUEVO_CODIGO NUMBER;
BEGIN 
    SELECT NVL(MAX(CODIGO_PRODUCTO)+1,1) INTO NUEVO_CODIGO FROM PRODUCTO;
    :NEW.CODIGO_PRODUCTO := NUEVO_CODIGO;
END;

CREATE OR REPLACE TRIGGER MINUSCULAS_PRODUCTO
BEFORE INSERT ON PRODUCTO FOR EACH ROW
DECLARE 
BEGIN 
    :NEW.NOMBRE := LOWER(:NEW.NOMBRE);
    :NEW.RESTRINGIDO := LOWER(:NEW.RESTRINGIDO);
END;

CREATE OR REPLACE TRIGGER ERRORES_NOMBRE_PRODUCTO
BEFORE INSERT ON PRODUCTO FOR EACH ROW 
DECLARE
    NOMBRE_PRODUCTO_ES_NULL EXCEPTION;
    NOMBRE_EN_USO EXCEPTION;
    REPETICION NUMBER;
BEGIN
    IF :NEW.NOMBRE IS NULL THEN
        RAISE NOMBRE_PRODUCTO_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICION FROM PRODUCTO WHERE NOMBRE = LOWER(:NEW.NOMBRE);
        IF REPETICION = 1 THEN
            RAISE NOMBRE_EN_USO;
        END IF;
    END IF;
EXCEPTION
    WHEN NOMBRE_PRODUCTO_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20060,'NOMBRE ES NULL');
    WHEN NOMBRE_EN_USO THEN
        RAISE_APPLICATION_ERROR(-20061,'NOMBRE YA ESTA REGISTRADO');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20062,'ERROR NO IDENTIFICADO EN NOMBRE PRODUCTO');
END;

CREATE OR REPLACE TRIGGER ERROR_PRECIO
BEFORE INSERT ON PRODUCTO FOR EACH ROW 
DECLARE
    PRECIO_ES_NULL EXCEPTION;
    PRECIO_INVALIDO EXCEPTION;
BEGIN
    IF :NEW.PRECIO IS NULL THEN
        RAISE PRECIO_ES_NULL;
    ELSE
        IF :NEW.PRECIO < 1 THEN
            RAISE PRECIO_INVALIDO;
        END IF;
    END IF;
EXCEPTION
    WHEN PRECIO_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20063,'PRECIO ES NULL');
    WHEN PRECIO_INVALIDO THEN
        RAISE_APPLICATION_ERROR(-20064,'PRECIO INVALIDO');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20065,'ERROR NO INDENTIFICADO EN PRECIO PRODUCTO');
END;

CREATE OR REPLACE TRIGGER ERROR_CATEGORIA_PRODUCTO
BEFORE INSERT ON PRODUCTO FOR EACH ROW 
DECLARE 
    CATEGORIA_ES_NULL EXCEPTION;
    CATEGORIA_INEXISTENTE EXCEPTION;
    REPETICION NUMBER;
BEGIN
    IF :NEW.CODIGO_CATEGORIA IS NULL THEN
        RAISE CATEGORIA_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICION FROM CATEGORIA WHERE CODIGO_CATEGORIA = :NEW.CODIGO_CATEGORIA;
        IF REPETICION = 0 THEN
            RAISE CATEGORIA_INEXISTENTE;
        END IF;
    END IF;
EXCEPTION 
    WHEN CATEGORIA_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20066,'CODIGO CATEGORIA ES NULL');
    WHEN CATEGORIA_INEXISTENTE THEN
        RAISE_APPLICATION_ERROR(-20067,'NO EXISTE ESE CODIGO DE CATEGORIA');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20068,'ERROR NO IDENTIFICADO EN LA CATEGORIA DE PRODUCTO');
END;

CREATE OR REPLACE TRIGGER ERROR_RESTRINGIDO
BEFORE INSERT ON PRODUCTO FOR EACH ROW
DECLARE 
    RESTRINGIDO_ES_NULL EXCEPTION;
    RESTRINGIDO_INVALIDO EXCEPTION;
BEGIN
    IF :NEW.RESTRINGIDO IS NULL THEN
        RAISE RESTRINGIDO_ES_NULL;
    ELSE
        :NEW.RESTRINGIDO := LOWER(:NEW.RESTRINGIDO);
        IF :NEW.RESTRINGIDO = 'si' OR :NEW.RESTRINGIDO = 'no' THEN 
            DBMS_OUTPUT.PUT_LINE('');
        ELSE
            RAISE RESTRINGIDO_INVALIDO;
        END IF;
    END IF;
EXCEPTION
    WHEN RESTRINGIDO_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20069,'RESTRINGIDO ES NULL');
    WHEN RESTRINGIDO_INVALIDO THEN
        RAISE_APPLICATION_ERROR(-20070,'SOLO SE ADMITE SI O NO');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20071,'ERROR NO REGISTRADO EN REGISTRO');
END;

CREATE OR REPLACE TRIGGER ERROR_STOCK_PRODUCTO
BEFORE INSERT ON PRODUCTO FOR EACH ROW 
DECLARE
    STOCK_ES_NULL EXCEPTION;
    STOCK_INVALIDO EXCEPTION;
BEGIN
    IF :NEW.STOCK IS NULL THEN
        RAISE STOCK_ES_NULL;
    ELSE
        IF :NEW.STOCK < 0 THEN
            RAISE STOCK_INVALIDO;
        END IF;
    END IF;
EXCEPTION
    WHEN STOCK_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20072,'STOCK ES NULL');
    WHEN STOCK_INVALIDO THEN
        RAISE_APPLICATION_ERROR(-20073,'STOCK INVALIDO');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20074,'CODIGO CATEGORIA ES NULL');
END;

-- BOLETA 

CREATE OR REPLACE TRIGGER CODIGO_BOLETA_AUTOMATICO
BEFORE INSERT ON BOLETA FOR EACH ROW 
DECLARE 
    NUEVO_CODIGO NUMBER;
BEGIN 
    SELECT NVL(MAX(CODIGO_BOLETA)+1,1) INTO NUEVO_CODIGO FROM BOLETA;
    :NEW.CODIGO_BOLETA := NUEVO_CODIGO;
END;

CREATE OR REPLACE TRIGGER CODIGO_SEGUIMIENTO_AUTOMATICO
BEFORE INSERT ON BOLETA FOR EACH ROW
DECLARE 
    ULTIMO_CODIGO NUMBER;
BEGIN 
    SELECT NVL(MAX(CODIGO_SEGUIMIENTO),1) INTO ULTIMO_CODIGO FROM DESPACHO;
    :NEW.CODIGO_SEGUIMIENTO := ULTIMO_CODIGO;
END;

CREATE OR REPLACE TRIGGER ERRORES_PAGO
BEFORE INSERT ON BOLETA FOR EACH ROW 
DECLARE 
    NOMBRE_PAGO_ES_NULL EXCEPTION;
    NUMERO_PAGO_ES_NULL EXCEPTION;
    FECHA_EXPIRACION_ES_NULL EXCEPTION;
    CVV_ES_NULL EXCEPTION;
BEGIN 
    IF :NEW.TIPO_PAGO.NOMBRE_PAGO IS NULL OR :NEW.TIPO_PAGO.NUMERO_TARJETA IS NULL OR :NEW.TIPO_PAGO.FECHA_EXPIRACION IS NULL THEN
        IF :NEW.TIPO_PAGO.NOMBRE_PAGO IS NULL THEN
            RAISE NOMBRE_PAGO_ES_NULL;
        ELSIF :NEW.TIPO_PAGO.NUMERO_TARJETA IS NULL THEN
            RAISE NUMERO_PAGO_ES_NULL;
        ELSE
            RAISE FECHA_EXPIRACION_ES_NULL;
        END IF;
    ELSE
        :NEW.TIPO_PAGO.NOMBRE_PAGO := LOWER(:NEW.TIPO_PAGO.NOMBRE_PAGO);
        IF :NEW.TIPO_PAGO.NOMBRE_PAGO = 'CREDITO' THEN
            IF :NEW.TIPO_PAGO.CVV IS NULL THEN
            RAISE  CVV_ES_NULL;
            END IF;
        END IF;
    END IF;
EXCEPTION
    WHEN NOMBRE_PAGO_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20080,'NOMBRE DE PAGO ES NULL');
    WHEN NUMERO_PAGO_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20081,'NUMERO DE PAGO ES NULL');
    WHEN FECHA_EXPIRACION_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20082,'FECHA DE EXPIRACION ES NULL');
    WHEN CVV_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20083,'CVV ES NULL');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20084,'ERROR NO IDENTIFICADO EN TIPO PAGO');
END;

-- DETALLE 

CREATE OR REPLACE TRIGGER CODIGO_BOLETA_EN_DETALLE
BEFORE INSERT ON DETALLE FOR EACH ROW
DECLARE
    ULTIMA_BOLETA NUMBER;
BEGIN
    SELECT NVL(MAX(CODIGO_BOLETA),1) INTO ULTIMA_BOLETA FROM BOLETA;
    :NEW.CODIGO_BOLETA := ULTIMA_BOLETA;
END;

CREATE OR REPLACE TRIGGER TOTAL_DETALLE
BEFORE INSERT ON DETALLE FOR EACH ROW 
DECLARE
    SUMATORIA NUMBER;
    PRECIO_PRODUCTO NUMBER;
BEGIN 
    SELECT PRECIO INTO PRECIO_PRODUCTO FROM PRODUCTO WHERE CODIGO_PRODUCTO = :NEW.CODIGO_PRODUCTO;
    :NEW.TOTAL := :NEW.CANTIDAD * PRECIO_PRODUCTO;
END;

CREATE OR REPLACE TRIGGER TOTAL_BOLETA
AFTER INSERT ON DETALLE FOR EACH ROW 
DECLARE
    TOTAL_BOLETA_ACTUAL NUMBER;
BEGIN
    SELECT TOTAL INTO TOTAL_BOLETA_ACTUAL FROM BOLETA WHERE CODIGO_BOLETA = :NEW.CODIGO_BOLETA;
    UPDATE BOLETA SET TOTAL = TOTAL_BOLETA_ACTUAL + :NEW.TOTAL WHERE CODIGO_BOLETA = :NEW.CODIGO_BOLETA;
END;

CREATE OR REPLACE TRIGGER ACTUALIZAR_STOCK
AFTER INSERT ON DETALLE FOR EACH ROW 
DECLARE 
    STOCK_ACTUAL NUMBER;
BEGIN 
    SELECT STOCK INTO STOCK_ACTUAL FROM PRODUCTO WHERE CODIGO_PRODUCTO = :NEW.CODIGO_PRODUCTO;
    UPDATE PRODUCTO SET STOCK = STOCK_ACTUAL - :NEW.CANTIDAD WHERE CODIGO_PRODUCTO = :NEW.CODIGO_PRODUCTO;
END;

-- CARRO

CREATE OR REPLACE TRIGGER CODIGO_CARRO_AUTOMATICO
BEFORE INSERT ON CARRO_TEMPORAL FOR EACH ROW
DECLARE 
    NUEVO_CODIGO NUMBER;
BEGIN
    SELECT NVL(MAX(CODIGO_CARRO)+1,1) INTO NUEVO_CODIGO  FROM CARRO_TEMPORAL;
    :NEW.CODIGO_CARRO := NUEVO_CODIGO;
END;

CREATE OR REPLACE TRIGGER ERRORES_RUT_CARRO
BEFORE INSERT ON CARRO_TEMPORAL FOR EACH ROW 
DECLARE 
    RUT_ES_NULL EXCEPTION;
    RUT_INEXISTENTE EXCEPTION;
    REPETICION NUMBER;
BEGIN 
    IF :NEW.RUT_CLIENTE IS NULL THEN
        RAISE RUT_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICION FROM CLIENTE WHERE RUT = :NEW.RUT_CLIENTE;
        IF REPETICION = 0 THEN
            RAISE RUT_INEXISTENTE;
        END IF;
    END IF;
EXCEPTION
    WHEN RUT_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20090,'EL RUT ES NULL');
    WHEN RUT_INEXISTENTE THEN
        RAISE_APPLICATION_ERROR(-20091,'EL REPARTIDOR NO ESTA INGRESADO');
    WHEN OTHERS THEN 
        RAISE_APPLICATION_ERROR(-20092,'ERROR NO IDENTIFICADO RUT DE DESPACHO');
END;

CREATE OR REPLACE TRIGGER ERROR_CARRO
BEFORE INSERT ON CARRO_TEMPORAL FOR EACH ROW 
DECLARE 
    CODIGO_PRODUCTO_ES_NULL EXCEPTION;
    CODIGO_PRODUCTO_INEXISTENTE EXCEPTION;
    CANTIDAD_ES_NULL EXCEPTION;
    CANTIDAD_INVALIDA EXCEPTION;
    MUCHA_DEMANDA EXCEPTION;
    REPETICION NUMBER;
    STOCK_PRODUCTO NUMBER;
BEGIN
    IF :NEW.CODIGO_PRODUCTO IS NULL THEN
        RAISE CODIGO_PRODUCTO_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICION FROM PRODUCTO WHERE CODIGO_PRODUCTO = :NEW.CODIGO_PRODUCTO;
        IF REPETICION = 0 THEN
            RAISE CODIGO_PRODUCTO_INEXISTENTE;
        ELSE
            IF :NEW.CANTIDAD IS NULL THEN
                RAISE CANTIDAD_ES_NULL;
            ELSE
                IF :NEW.CANTIDAD < 1 THEN
                    RAISE CANTIDAD_INVALIDA;
                ELSE
                    SELECT STOCK INTO STOCK_PRODUCTO FROM PRODUCTO WHERE CODIGO_PRODUCTO = :NEW.CODIGO_PRODUCTO;
                    IF :NEW.CANTIDAD > STOCK_PRODUCTO THEN
                        RAISE MUCHA_DEMANDA;
                    END IF;
                END IF;
            END IF;
        END IF;
    END IF;
EXCEPTION
    WHEN CODIGO_PRODUCTO_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20090,'CODIGO PRODUCTO ES NULL');
    WHEN CODIGO_PRODUCTO_INEXISTENTE THEN
        RAISE_APPLICATION_ERROR(-20091,'ESE CODIGO DE PRODUCTO NO EXISTE');
    WHEN CANTIDAD_ES_NULL THEN
        RAISE_APPLICATION_ERROR(-20092,'CANTIDAD ES NULL');
    WHEN CANTIDAD_INVALIDA THEN
        RAISE_APPLICATION_ERROR(-20093,'NO SE PUEDE INGRESAR ESA CANTIDAD');
    WHEN MUCHA_DEMANDA THEN
        RAISE_APPLICATION_ERROR(-20094,'PIDIO MAS CANTIAD DISPONIBLE EN EL STOCK');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20095,'ERROR NO IDENTIFICADO EN DETALLE');
END;

CREATE OR REPLACE TRIGGER ERRORES_RUT_EDAD
BEFORE INSERT ON CARRO_TEMPORAL FOR EACH ROW 
DECLARE
    MENOR_DE_18 EXCEPTION;
    MENOR_DE_14 EXCEPTION;
    RESTRICION_PRODUCTO VARCHAR(2);
    NACIMIENTO_CLIENTE DATE;
    EDAD NUMBER;
BEGIN
    SELECT FECHA_NACIMIENTO INTO NACIMIENTO_CLIENTE FROM CLIENTE WHERE RUT = :NEW.RUT_CLIENTE;
    EDAD := OBTENER_EDAD(NACIMIENTO_CLIENTE);
    SELECT RESTRINGIDO INTO RESTRICION_PRODUCTO FROM PRODUCTO WHERE CODIGO_PRODUCTO = :NEW.CODIGO_PRODUCTO;
    IF RESTRICION_PRODUCTO = 'si' THEN
        IF EDAD < 18 THEN
            RAISE MENOR_DE_18;
        END IF;
    ELSE
        IF EDAD < 14 THEN
            RAISE MENOR_DE_14;
        END IF;
    END IF;
EXCEPTION
    WHEN MENOR_DE_18 THEN
        RAISE_APPLICATION_ERROR(-20096,'DEBE TENER ALMENOS 18 AÑOS PARA COMPRAR ESTE PRODUCTO');
    WHEN MENOR_DE_14 THEN
        RAISE_APPLICATION_ERROR(-20097,'DEBE TENER ALMENOS 14 AÑOS PARA COMPRAR ESTE PRODUCTO');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20098,'ERROR NO IDENTIFICADO AL COMPROBAR EDAD');
END;

CREATE OR REPLACE TRIGGER TOTAL_CARRO
BEFORE INSERT ON CARRO_TEMPORAL FOR EACH ROW 
DECLARE
    SUMATORIA NUMBER;
    PRECIO_PRODUCTO NUMBER;
BEGIN 
    SELECT PRECIO INTO PRECIO_PRODUCTO FROM PRODUCTO WHERE CODIGO_PRODUCTO = :NEW.CODIGO_PRODUCTO;
    :NEW.TOTAL := :NEW.CANTIDAD * PRECIO_PRODUCTO;
END;

---

CALL CREAR_BASE(); 

DECLARE
    MENSAJE VARCHAR(20);
BEGIN
    INGRESAR_CARRO_TEMPORAL(20305990,6,11,MENSAJE);
    DBMS_OUTPUT.put_line (MENSAJE);
END;

SELECT * FROM REPARTIDOR;
SELECT * FROM DESPACHO;
SELECT * FROM CATEGORIA;
SELECT * FROM PRODUCTO;
SELECT * FROM CLIENTE;
SELECT * FROM BOLETA;
SELECT * FROM DETALLE;
SELECT * FROM CARRO_TEMPORAL;
