CREATE OR REPLACE PROCEDURE TRABAJO_2.ACTUALIZAR_NOMBRE_PRODUCTO(
    CODIGO_PRODUCTO_ENTRADA IN PRODUCTO.CODIGO_PRODUCTO%TYPE,
    NOMBRE_NUEVO_ENTRADA IN PRODUCTO.NOMBRE%TYPE 
)
IS 
    REPETICIONES_CODIGO NUMBER;
    REPETICIONES_NOMBRE NUMBER;
    CODIGO_PRODUCTO_ES_NULL EXCEPTION;
    PRODUCTO_INEXISTENTE EXCEPTION;
    NOMBRE_NUEVO_ES_NULL EXCEPTION;
    NOMBRE_YA_EN_USO EXCEPTION;
BEGIN
    LOCK TABLE PRODUCTO IN ROW EXCLUSIVE MODE;
    IF CODIGO_PRODUCTO_ENTRADA IS NULL THEN
        RAISE CODIGO_PRODUCTO_ES_NULL;
    END IF;
    SELECT COUNT(*) INTO REPETICIONES_CODIGO FROM PRODUCTO
    WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
    IF REPETICIONES_CODIGO = 0 THEN
        RAISE PRODUCTO_INEXISTENTE;
    ELSE
        IF NOMBRE_NUEVO_ENTRADA IS NULL THEN
            RAISE NOMBRE_NUEVO_ES_NULL;
        END IF;
        SELECT COUNT(*) INTO REPETICIONES_NOMBRE FROM PRODUCTO
        WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
        IF REPETICIONES_NOMBRE < 0 THEN
            RAISE NOMBRE_YA_EN_USO;
        ELSE
            UPDATE PRODUCTO
            SET NOMBRE = NOMBRE_NUEVO_ENTRADA
            WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    
    
    EXCEPTION
        WHEN CODIGO_PRODUCTO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('CODIGO PRODUCTO ES NULL');
            ROLLBACK;
        WHEN PRODUCTO_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('NO EXISTE ESE PRODUCTO');
            ROLLBACK;
        WHEN NOMBRE_NUEVO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL NUEVO NOMBRE ES NULL');
            ROLLBACK;
        WHEN NOMBRE_YA_EN_USO THEN
            DBMS_OUTPUT.PUT_LINE('ESE NOMBRE DE PRODUCTO NO ESTA DISPONIBLE');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
