CREATE OR REPLACE PROCEDURE TRABAJO_2.ACTUALIZAR_CORREO_CLIENTE(
    RUT_ENTRADA IN CLIENTE.RUT%TYPE,
    NUEVO_CORREO IN CLIENTE.CORREO%TYPE 
)
IS 
    REPETICIONES_RUT NUMBER;
    REPETICIONES_CORREO NUMBER;
    RUT_ES_NULL EXCEPTION;
    CLIENTE_INEXISTENTE EXCEPTION;
    NUEVO_CORREO_ES_NULL EXCEPTION;
    CORREO_YA_EN_USO EXCEPTION;
BEGIN
    LOCK TABLE CLIENTE IN ROW EXCLUSIVE MODE;
    IF RUT_ENTRADA IS NULL THEN
        RAISE RUT_ES_NULL;
    END IF;
    SELECT COUNT(*) INTO REPETICIONES_RUT FROM CLIENTE
    WHERE RUT = RUT_ENTRADA;
    IF REPETICIONES_RUT = 0 THEN
        RAISE CLIENTE_INEXISTENTE;
    ELSE
        IF NUEVO_CORREO IS NULL THEN
            RAISE NUEVO_CORREO_ES_NULL;
        END IF;
        SELECT COUNT(*) INTO REPETICIONES_CORREO FROM CLIENTE
        WHERE CORREO = NUEVO_CORREO;
        IF REPETICIONES_CORREO = 1 THEN
            RAISE CORREO_YA_EN_USO;
        ELSE
            UPDATE CLIENTE
            SET CORREO = NUEVO_CORREO
            WHERE RUT = RUT_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    
    EXCEPTION
        WHEN RUT_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('RUT ES NULL');
            ROLLBACK;
        WHEN CLIENTE_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('NO EXISTE ESE CLIENTE');
            ROLLBACK;
        WHEN NUEVO_CORREO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('CORREO ES NULL');
            ROLLBACK;
        WHEN CORREO_YA_EN_USO THEN
            DBMS_OUTPUT.PUT_LINE('ESE CORREO NO ESTA DISPONIBLE');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
