CREATE OR REPLACE PROCEDURE TRABAJO_2.ACTUALIZAR_TOTAL(
    CODIGO_BOLETA_ENTRADA IN BOLETA.CODIGO_BOLETA%TYPE,
    NUEVO_TOTAL IN BOLETA.TOTAL%TYPE
)
IS 
    REPETICIONES_BOLETA NUMBER;
    CODIGO_BOLETA_ES_NULL EXCEPTION;
    BOLETA_INEXISTENTE EXCEPTION;
    NUEVO_TOTAL_ES_NULL EXCEPTION;
    TOTAL_INVALIDO EXCEPTION;
BEGIN
    LOCK TABLE BOLETA IN ROW EXCLUSIVE MODE;
    IF CODIGO_BOLETA_ENTRADA IS NULL THEN
        RAISE CODIGO_BOLETA_ES_NULL;
    END IF;
    SELECT COUNT(*) INTO REPETICIONES_BOLETA FROM BOLETA
    WHERE CODIGO_BOLETA = CODIGO_BOLETA_ENTRADA;
    IF REPETICIONES_BOLETA = 0 THEN
        RAISE BOLETA_INEXISTENTE;
    ELSE
        IF NUEVO_TOTAL IS NULL THEN
            RAISE NUEVO_TOTAL_ES_NULL;
        ELSIF NUEVO_TOTAL < 1 THEN
            RAISE TOTAL_INVALIDO;
        ELSE
            UPDATE BOLETA
            SET TOTAL = NUEVO_TOTAL
            WHERE CODIGO_BOLETA = CODIGO_BOLETA_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    EXCEPTION
        WHEN CODIGO_BOLETA_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('CODIGO BOLETA ES NULL');
            ROLLBACK;
        WHEN BOLETA_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('NO EXISTE UNA BOLETA CON ESE CODIGO');
            ROLLBACK;
        WHEN NUEVO_TOTAL_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL NUEVO TOTAL ES NULL');
            ROLLBACK;
        WHEN TOTAL_INVALIDO THEN
            DBMS_OUTPUT.PUT_LINE('LOS COSTOS DE LOS PRODCUTOS DEBEN SER 1 O MAYOR');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
