CREATE OR REPLACE PROCEDURE TRABAJO_2.ACTUALIZAR_NOMBRE_CATEGORIA(
    CODIGO_CATEGORIA_ENTRADA IN CATEGORIA.CODIGO_CATEGORIA%TYPE,
    NOMBRE_NUEVO_ENTRADA IN CATEGORIA.NOMBRE_CATEGORIA%TYPE 
)
IS 
    REPETICIONES_CODIGO NUMBER;
    REPETICIONES_NOMBRE NUMBER;
    CODIGO_CATEGORIA_ES_NULL EXCEPTION;
    CATEGORIA_INEXISTENTE EXCEPTION;
    NOMBRE_NUEVO_ES_NULL EXCEPTION;
    NOMBRE_NO_DISPONIBLE EXCEPTION;
BEGIN
    LOCK TABLE CATEGORIA IN ROW EXCLUSIVE MODE;
    IF CODIGO_CATEGORIA_ENTRADA IS NULL THEN
        RAISE CODIGO_CATEGORIA_ES_NULL;
    END IF;
    SELECT COUNT(*) INTO REPETICIONES_CODIGO FROM CATEGORIA
    WHERE CODIGO_CATEGORIA = CODIGO_CATEGORIA_ENTRADA;
    IF REPETICIONES_CODIGO = 0 THEN
        RAISE CATEGORIA_INEXISTENTE;
    ELSE
        IF NOMBRE_NUEVO_ENTRADA IS NULL THEN
            RAISE NOMBRE_NUEVO_ES_NULL;
        END IF;
        SELECT NOMBRE_CATEGORIA INTO REPETICIONES_NOMBRE FROM CATEGORIA
        WHERE CODIGO_CATEGORIA = CODIGO_CATEGORIA_ENTRADA;
        IF REPETICIONES_NOMBRE = 1 THEN
            RAISE NOMBRE_NO_DISPONIBLE;
        ELSE
            UPDATE CATEGORIA 
            SET NOMBRE_CATEGORIA = NOMBRE_NUEVO_ENTRADA
            WHERE CODIGO_CATEGORIA = CODIGO_CATEGORIA_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    
    EXCEPTION
        WHEN CODIGO_CATEGORIA_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL CODIGO CATEGORIA ES NULL');
            ROLLBACK;
        WHEN CATEGORIA_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('NO EXISTE ESE CODIGO DE CATEGORIA');
            ROLLBACK;
        WHEN NOMBRE_NUEVO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL NUEVO NOMBRE ES NULL');
            ROLLBACK;
        WHEN NOMBRE_NO_DISPONIBLE THEN
            DBMS_OUTPUT.PUT_LINE('ESE NOMBRE ESTA SIENDO USANDO EN OTRA CATEGORIA');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
