CREATE OR REPLACE PROCEDURE TRABAJO_2.ACTUALIZAR_FECHA(
    CODIGO_BOLETA_ENTRADA IN BOLETA.CODIGO_BOLETA%TYPE,
    NUEVA_FECHA IN BOLETA.FECHA%TYPE
)
IS 
    REPETICIONES_BOLETA NUMBER;
    CODIGO_BOLETA_ES_NULL EXCEPTION;
    BOLETA_INEXISTENTE EXCEPTION;
    NUEVA_FECHA_ES_NULL EXCEPTION;
BEGIN
    LOCK TABLE BOLETA IN ROW EXCLUSIVE MODE;
    IF CODIGO_BOLETA_ENTRADA IS NULL THEN
        RAISE CODIGO_BOLETA_ES_NULL;
    END IF;
    SELECT COUNT(*) INTO REPETICIONES_BOLETA FROM BOLETA
    WHERE CODIGO_BOLETA = CODIGO_BOLETA_ENTRADA;
    IF REPETICIONES_BOLETA = 0 THEN
        RAISE BOLETA_INEXISTENTE;
    ELSE
        IF NUEVA_FECHA IS NULL THEN
            RAISE NUEVA_FECHA_ES_NULL;
        ELSE
            UPDATE BOLETA
            SET FECHA = NUEVA_FECHA
            WHERE CODIGO_BOLETA = CODIGO_BOLETA_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    EXCEPTION
        WHEN CODIGO_BOLETA_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL CODIGO BOTELA ES NULL');
            ROLLBACK;
        WHEN BOLETA_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('NO EXISTE UNA BOLETA CON ESE CODIGO');
            ROLLBACK;
        WHEN NUEVA_FECHA_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('LA FECHA ES NULL');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
