CREATE OR REPLACE PROCEDURE TRABAJO_2.ACTUALIZAR_APELLIDO_CLIENTE(
    RUT_ENTRADA IN CLIENTE.RUT%TYPE,
    NUEVO_APELLIDO IN CLIENTE.APELLIDO%TYPE 
)
IS 
    REPETICIONES_RUT NUMBER;
    RUT_ES_NULL EXCEPTION;
    CLIENTE_INEXISTENTE EXCEPTION;
    APELLIDO_ES_NULL EXCEPTION;
BEGIN
    LOCK TABLE CLIENTE IN ROW EXCLUSIVE MODE;
    IF RUT_ENTRADA IS NULL THEN 
        RAISE RUT_ES_NULL;
    END IF;
    SELECT COUNT(*) INTO REPETICIONES_RUT FROM CLIENTE
    WHERE RUT = RUT_ENTRADA;
    IF REPETICIONES_RUT = 0 THEN
        RAISE CLIENTE_INEXISTENTE;
    ELSE
        IF NUEVO_APELLIDO IS NULL THEN
            RAISE APELLIDO_ES_NULL;
        ELSE
            UPDATE CLIENTE
            SET APELLIDO = NUEVO_APELLIDO
            WHERE RUT = RUT_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    
    EXCEPTION
        WHEN RUT_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('RUT ES NULL');
            ROLLBACK;
        WHEN CLIENTE_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('NO EXISTE ESE CLIENTE');
            ROLLBACK;
        WHEN APELLIDO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('APELLIDO ES NULL');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
