CREATE OR REPLACE PROCEDURE TRABAJO_2.ACTUALIZAR_NOMBRE_CLIENTE(
    RUT_ENTRADA IN CLIENTE.RUT%TYPE,
    NUEVO_NOMBRE IN CLIENTE.NOMBRE%TYPE 
)
IS 
    REPETICIONES_RUT NUMBER;
    RUT_ES_NULL EXCEPTION;
    CLIENTE_INEXISTENTE EXCEPTION;
    NUEVO_NOMBRE_ES_NULL EXCEPTION;
BEGIN
    LOCK TABLE CLIENTE IN ROW EXCLUSIVE MODE;
    IF RUT_ENTRADA IS NULL THEN
        RAISE RUT_ES_NULL;
    END IF;
    SELECT COUNT(*) INTO REPETICIONES_RUT FROM CLIENTE
    WHERE RUT = RUT_ENTRADA;
    IF REPETICIONES_RUT = 0 THEN
        RAISE CLIENTE_INEXISTENTE;
    ELSE
        IF NUEVO_NOMBRE IS NULL THEN
            RAISE NUEVO_NOMBRE_ES_NULL;
        ELSE
            UPDATE CLIENTE
            SET NOMBRE = NUEVO_NOMBRE
            WHERE RUT = RUT_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    
    EXCEPTION
        WHEN RUT_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('RUT ES NULL');
            ROLLBACK;
        WHEN CLIENTE_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('NO EXISTE ESE CLIENTE');
            ROLLBACK;
        WHEN NUEVO_NOMBRE_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL NUEVO NOMBRE ES NULL');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
