CREATE OR REPLACE PROCEDURE TRABAJO_2.ACTUALIZAR_CATEGORIA(
    CODIGO_PRODUCTO_ENTRADA IN PRODUCTO.CODIGO_PRODUCTO%TYPE,
    CODIGO_CATEGORIA_ENTRADA IN PRODUCTO.CODIGO_CATEGORIA %TYPE
)
IS 
    REPETICIONES_CODIGO_PRODUCTO NUMBER;
    REPETICIONES_CODIGO_CATEGORIA NUMBER;
    CODIGO_PRODUCTO_ES_NULL EXCEPTION;
    PRODUCTO_INEXISTENTE EXCEPTION;
    CODIGO_CATEGORIA_ES_NULL EXCEPTION;
    CATEGORIA_INEXISTENTE EXCEPTION;
BEGIN
    LOCK TABLE PRODUCTO IN ROW EXCLUSIVE MODE;
    IF CODIGO_PRODUCTO_ENTRADA IS NULL THEN
        RAISE CODIGO_PRODUCTO_ES_NULL;
    END IF;
    SELECT COUNT(*) INTO REPETICIONES_CODIGO_PRODUCTO FROM PRODUCTO
    WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
    IF REPETICIONES_CODIGO_PRODUCTO = 0 THEN
        RAISE PRODUCTO_INEXISTENTE;
    ELSE
        IF CODIGO_CATEGORIA_ENTRADA IS NULL THEN
            RAISE CODIGO_CATEGORIA_ES_NULL;
        END IF;
        SELECT COUNT(*) INTO REPETICIONES_CODIGO_CATEGORIA FROM CATEGORIA
        WHERE CODIGO_CATEGORIA = CODIGO_CATEGORIA_ENTRADA;
        IF REPETICIONES_CODIGO_CATEGORIA = 0 THEN
            RAISE CATEGORIA_INEXISTENTE;
        ELSE
            UPDATE PRODUCTO
            SET CODIGO_CATEGORIA = CODIGO_CATEGORIA_ENTRADA
            WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    
    EXCEPTION
        WHEN CODIGO_PRODUCTO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('CODIGO PRODUCTO ES NULL');
            ROLLBACK;
        WHEN PRODUCTO_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('ESE PRODUCTO NO EXISTE');
            ROLLBACK;
        WHEN CATEGORIA_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('NO EXISTE ESE CODIGO DE CATEGORIA');
            ROLLBACK;
        WHEN CODIGO_CATEGORIA_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('CODIGO CATEGORIA ES NULL');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
