CREATE OR REPLACE PROCEDURE TRABAJO_2.ACTUALIZAR_EDAD_CLIENTE(
    RUT_ENTRADA IN CLIENTE.RUT%TYPE,
    NUEVA_EDAD IN CLIENTE.EDAD%TYPE 
)
IS 
    REPETICIONES_RUT NUMBER;
    RUT_ES_NULL EXCEPTION;
    CLIENTE_INEXISTENTE EXCEPTION;
    NUEVA_EDAD_ES_NULL EXCEPTION;
    EDAD_INVALIDA EXCEPTION;
BEGIN
    LOCK TABLE CLIENTE IN ROW EXCLUSIVE MODE;
    IF RUT_ENTRADA IS NULL THEN
        RAISE RUT_ES_NULL;
    END IF;
    SELECT COUNT(*) INTO REPETICIONES_RUT FROM CLIENTE
    WHERE RUT = RUT_ENTRADA;
    IF REPETICIONES_RUT = 0 THEN
        RAISE CLIENTE_INEXISTENTE;
    ELSE
        IF NUEVA_EDAD IS NULL THEN
            RAISE NUEVA_EDAD_ES_NULL;
        ELSIF NUEVA_EDAD < 0 OR NUEVA_EDAD > 120 THEN
            RAISE EDAD_INVALIDA;
        ELSE
            UPDATE CLIENTE
            SET EDAD = NUEVA_EDAD
            WHERE RUT = RUT_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    
    EXCEPTION
        WHEN RUT_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('RUT ES NULL');
            ROLLBACK;
        WHEN CLIENTE_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('NO EXISTE ESE CLIENTE');
            ROLLBACK;
        WHEN NUEVA_EDAD_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('LA EDAD ES NULL');
            ROLLBACK;
        WHEN EDAD_INVALIDA THEN
            DBMS_OUTPUT.PUT_LINE('NO SE PUEDE INGRESAR ESA EDAD');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
