CREATE OR REPLACE PROCEDURE TRABAJO_2.COMPRAR_PRODUCTO(
    CODIGO_PRODUCTO_ENTRADA IN PRODUCTO.CODIGO_PRODUCTO%TYPE,
    CANTIDAD_PRODUCTOS_COMPRADOS IN NUMBER
)   
IS 
    CANTIDAD_STOCK NUMBER;
    REPETICIONES_CODIGO NUMBER;
    CODIGO_PRODUCTO_ES_NULL EXCEPTION;
    PRODUCTO_INEXISTENTE EXCEPTION;
    CANTIDAD_COMPRADOS_ES_NULL EXCEPTION;
    STOCK_INSUFICIENTE EXCEPTION;
    CANTIDAD_INVALIDA EXCEPTION;
BEGIN
    LOCK TABLE PRODUCTO IN ROW EXCLUSIVE MODE;
    IF CODIGO_PRODUCTO_ENTRADA IS NULL THEN
        RAISE CODIGO_PRODUCTO_ES_NULL;
    END IF;
    SELECT COUNT(*) INTO REPETICIONES_CODIGO FROM PRODUCTO WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
    IF REPETICIONES_CODIGO = 0 THEN
        RAISE PRODUCTO_INEXISTENTE;
    ELSE
        IF CANTIDAD_PRODUCTOS_COMPRADOS IS NULL THEN
            RAISE CANTIDAD_COMPRADOS_ES_NULL;
        END IF;
        SELECT STOCK INTO CANTIDAD_STOCK FROM PRODUCTO WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
        IF CANTIDAD_PRODUCTOS_COMPRADOS > CANTIDAD_STOCK THEN
            RAISE STOCK_INSUFICIENTE;
        ELSIF CANTIDAD_PRODUCTOS_COMPRADOS <= 0 THEN
            RAISE CANTIDAD_INVALIDA;
        ELSE
            UPDATE PRODUCTO
            SET STOCK = CANTIDAD_STOCK - CANTIDAD_PRODUCTOS_COMPRADOS
            WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
            COMMIT;
            DBMS_OUTPUT.PUT_LINE('EXISTE UN NUEVO STOCK');
        END IF;
    END IF;
    
    EXCEPTION
        WHEN CODIGO_PRODUCTO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('CODIGO PRODUCTO ES NULL');
            ROLLBACK;
        WHEN PRODUCTO_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('ESE PRODUCTO NO EXISTE');
            ROLLBACK;
        WHEN CANTIDAD_COMPRADOS_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('NO PUEDE COMPRAR NULL PRODUCTOS');
            ROLLBACK;
        WHEN STOCK_INSUFICIENTE THEN
            DBMS_OUTPUT.PUT_LINE('NO PUEDE COMPRAR ESA CANTIDA DE PRODUCTOS');
            ROLLBACK;
        WHEN CANTIDAD_INVALIDA THEN
            DBMS_OUTPUT.PUT_LINE('NO PUEDE COMPRAR CANTIDADES NEGATIVAS');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
