CREATE OR REPLACE PROCEDURE TRABAJO_2.ELIMINAR_CLIENTE(
    RUT_ENTRADA IN CLIENTE.RUT%TYPE
)
IS 
    REPETICIONES_RUT NUMBER;
    RUT_ES_NULL EXCEPTION;
    RUT_INEXISTENTE EXCEPTION;
BEGIN
    LOCK TABLE CLIENTE IN ROW EXCLUSIVE MODE;
    IF RUT_ENTRADA IS NULL THEN
        RAISE RUT_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICIONES_RUT FROM CLIENTE
        WHERE RUT = RUT_ENTRADA;
        IF REPETICIONES_RUT = 0 THEN
            RAISE RUT_INEXISTENTE;
        ELSE
            DELETE FROM BOLETA WHERE RUT = RUT_ENTRADA;
            DELETE FROM CLIENTE WHERE RUT = RUT_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    
    EXCEPTION
        WHEN RUT_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('RUT ES NULL');
            ROLLBACK;
        WHEN RUT_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('ESE RUT NO EXISTE');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
