CREATE OR REPLACE PROCEDURE TRABAJO_2.ELIMINAR_PRODCTO(
    CODIGO_PRODUCTO_ENTRADA IN PRODUCTO.CODIGO_PRODUCTO%TYPE
)
IS 
    REPETICIONES_CODIGO NUMBER;
    CODIGO_ES_NULL EXCEPTION;
    PRODUCTO_INEXISTENTE EXCEPTION;
BEGIN
    IF CODIGO_PRODUCTO_ENTRADA IS NULL THEN
        RAISE CODIGO_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICIONES_CODIGO FROM PRODUCTO
        WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
        IF REPETICIONES_CODIGO = 0 THEN
            RAISE PRODUCTO_INEXISTENTE;
        ELSE
            LOCK TABLE PRODUCTO IN ROW EXCLUSIVE MODE;
            DELETE FROM BOLETA WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
            DELETE FROM PRODUCTO WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    
    EXCEPTION
        WHEN CODIGO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('CODIGO DE PRODUCTO ES NULL');
            ROLLBACK;
        WHEN PRODUCTO_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('ESE PRODUCTO NO EXISTE');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
