CREATE OR REPLACE PROCEDURE TRABAJO_2.ELIMINAR_CATEGORIA(
    CODIGO_CATEGORIA_ENTRADA IN CATEGORIA.CODIGO_CATEGORIA%TYPE
)
IS 
    REPETICIONES_CODIGO NUMBER;
    CODIGO_PRODUCTO_A_ELIMINAR NUMBER;
    CANTIDAD_PRODUCTOS NUMBER;
    CODIGO_ES_NULL EXCEPTION;
    CATEGORIA_INEXISTENTE EXCEPTION;
BEGIN
    IF CODIGO_CATEGORIA_ENTRADA IS NULL THEN
        RAISE CODIGO_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICIONES_CODIGO FROM CATEGORIA
        WHERE CODIGO_CATEGORIA = CODIGO_CATEGORIA_ENTRADA;
        IF REPETICIONES_CODIGO = 0 THEN
            RAISE CATEGORIA_INEXISTENTE;
        ELSE
            LOCK TABLE CATEGORIA IN ROW EXCLUSIVE MODE;
            SELECT COUNT(*) INTO CANTIDAD_PRODUCTOS FROM PRODUCTO
            WHERE CODIGO_CATEGORIA = CODIGO_CATEGORIA_ENTRADA;
            WHILE CANTIDAD_PRODUCTOS > 0 LOOP
                SELECT MAX(CODIGO_PRODUCTO) INTO CODIGO_PRODUCTO_A_ELIMINAR FROM PRODUCTO
                WHERE CODIGO_CATEGORIA = CODIGO_CATEGORIA_ENTRADA;
                DELETE FROM BOLETA WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_A_ELIMINAR;
                DELETE FROM PRODUCTO WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_A_ELIMINAR;
                CANTIDAD_PRODUCTOS := CANTIDAD_PRODUCTOS - 1;
            END LOOP;
            DELETE FROM CATEGORIA WHERE CODIGO_CATEGORIA = CODIGO_CATEGORIA_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    
    EXCEPTION
        WHEN CODIGO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('CODIGO DE CATEGORIA ES NULL');
            ROLLBACK;
        WHEN CATEGORIA_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('ESA CATEGORIA NO EXISTE');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
