CREATE OR REPLACE PROCEDURE TRABAJO_2.ELIMINAR_BOLETA(
    CODIGO_BOLETA_ENTRADA IN BOLETA.CODIGO_BOLETA%TYPE
)
IS 
   REPETICIONES_CODIGO NUMBER;
    CODIGO_ES_NULL EXCEPTION;
    CODIGO_INEXISTENTE EXCEPTION;
BEGIN
    LOCK TABLE BOLETA IN ROW EXCLUSIVE MODE;
    IF CODIGO_BOLETA_ENTRADA IS NULL THEN
        RAISE CODIGO_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICIONES_CODIGO FROM BOLETA
        WHERE CODIGO_BOLETA = CODIGO_BOLETA_ENTRADA;
        IF REPETICIONES_CODIGO = 0 THEN
            RAISE CODIGO_INEXISTENTE;
        ELSE
            DELETE FROM BOLETA WHERE CODIGO_BOLETA = CODIGO_BOLETA_ENTRADA;
            COMMIT;
        END IF;
    END IF;
    
    EXCEPTION
        WHEN CODIGO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('ESE CODIGO DE BOLETA');
            ROLLBACK;
        WHEN CODIGO_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('ESE CODIGO DE BOLETA');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
