CREATE OR REPLACE PROCEDURE TRABAJO_2.INSERTAR_CLIENTE(
    RUT_ENTRADA IN CLIENTE.RUT%TYPE,
    NOMBRE_ENTRADA IN CLIENTE.NOMBRE%TYPE,
    APELLIDO_ENTRADA IN CLIENTE.APELLIDO%TYPE,
    CORREO_ENTRADA IN CLIENTE.CORREO%TYPE,
    EDAD_ENTRADA IN CLIENTE.EDAD%TYPE
)
IS
    REPETICION_RUT NUMBER;
    REPETICION_CORREO NUMBER;
    RUT_ES_NULL EXCEPTION;
    NOMBRE_ES_NULL EXCEPTION;
    APELLIDO_ES_NULL EXCEPTION;
    CORREO_ES_NULL EXCEPTION;
    EDAD_ES_NULL EXCEPTION;
    RUT_YA_EN_USO EXCEPTION;
    RUT_INVALIDO EXCEPTION;
    CORREO_YA_EN_USO EXCEPTION;
    EDAD_INVALIDA EXCEPTION;
BEGIN
    LOCK TABLE CLIENTE IN ROW EXCLUSIVE MODE;
    SELECT COUNT(*) INTO REPETICION_RUT
    FROM CLIENTE c 
    WHERE RUT = RUT_ENTRADA;
    SELECT COUNT(*) INTO REPETICION_CORREO
    FROM CLIENTE
    WHERE CORREO = CORREO_ENTRADA;
    -- NULL
    IF RUT_ENTRADA IS NULL OR NOMBRE_ENTRADA IS NULL OR APELLIDO_ENTRADA IS NULL OR CORREO_ENTRADA IS NULL OR EDAD_ENTRADA IS NULL THEN
        IF RUT_ENTRADA IS NULL THEN
            RAISE RUT_ES_NULL;
        ELSIF NOMBRE_ENTRADA IS NULL THEN
            RAISE NOMBRE_ES_NULL;
        ELSIF APELLIDO_ENTRADA IS NULL THEN 
            RAISE APELLIDO_ES_NULL;
        ELSIF CORREO_ENTRADA IS NULL THEN 
            RAISE CORREO_ES_NULL;
        ELSE 
            RAISE EDAD_ES_NULL;
        END IF;
    -- RUT
    ELSIF REPETICION_RUT = 1 THEN
        RAISE RUT_YA_EN_USO;
    ELSIF RUT_ENTRADA <= 4000000 OR RUT_ENTRADA >= 28000000 THEN
        RAISE RUT_INVALIDO;
    -- CORREO
    ELSIF REPETICION_CORREO = 1 THEN
        RAISE CORREO_YA_EN_USO;
    -- EDAD
    ELSIF EDAD_ENTRADA < 0 OR EDAD_ENTRADA >= 120 THEN
        RAISE EDAD_INVALIDA;
    ELSE
        INSERT INTO CLIENTE VALUES(RUT_ENTRADA,NOMBRE_ENTRADA,APELLIDO_ENTRADA,CORREO_ENTRADA,EDAD_ENTRADA);
        DBMS_OUTPUT.PUT_LINE('DATOS INGRESADOS');
        COMMIT;
    END IF;

    EXCEPTION
        -- NULL
        WHEN RUT_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL RUT ES NULL');
            ROLLBACK;
        WHEN NOMBRE_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL NOMBRE ES NULL');
            ROLLBACK;
        WHEN APELLIDO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL APELLIDO ES NULL');
            ROLLBACK;
        WHEN CORREO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL CORREO ES NULL');
            ROLLBACK;
        WHEN EDAD_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL EDAD ES NULL');
            ROLLBACK;
        -- RUT
        WHEN RUT_YA_EN_USO THEN
            DBMS_OUTPUT.PUT_LINE('ESE RUT YA ESTA REGISTRADO');
            ROLLBACK;
        WHEN RUT_INVALIDO THEN
            DBMS_OUTPUT.PUT_LINE('NO SE PUEDE INGRESAR ESE RUT');
            ROLLBACK;
        -- CORREO
        WHEN CORREO_YA_EN_USO THEN
            DBMS_OUTPUT.PUT_LINE('ESE CORREO YA ESTA EN USO');
            ROLLBACK;
        -- EDAD
        WHEN EDAD_INVALIDA THEN
            DBMS_OUTPUT.PUT_LINE('NO SE PUEDE INGRESAR ESA EDAD');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
