CREATE OR REPLACE PROCEDURE TRABAJO_2.INSERTAR_CATEGORIA(
    CODIGO_CATEGORIA_ENTRADA IN CATEGORIA.CODIGO_CATEGORIA%TYPE,
    NOMBRE_CATEGORIA_ENTRADA IN CATEGORIA.NOMBRE_CATEGORIA%TYPE
)
IS
    REPETICION_CODIGO NUMBER;
    REPETICION_NOMBRE NUMBER;
    CODIGO_CATEGORIA_ES_NULL EXCEPTION;
    NOMBRE_CATEGORIA_ES_NULL EXCEPTION;
    CODIGO_YA_EN_USO EXCEPTION;
    CODIGO_INVALIDO EXCEPTION;
    NOMBRE_YA_EN_USO EXCEPTION;
BEGIN
    LOCK TABLE CATEGORIA IN ROW EXCLUSIVE MODE;
    SELECT COUNT(*) INTO REPETICION_CODIGO 
    FROM CATEGORIA
    WHERE CODIGO_CATEGORIA = CODIGO_CATEGORIA_ENTRADA;
    SELECT COUNT(*) INTO REPETICION_NOMBRE 
    FROM CATEGORIA
    WHERE NOMBRE_CATEGORIA = NOMBRE_CATEGORIA_ENTRADA;
    -- NULL
    IF CODIGO_CATEGORIA_ENTRADA IS NULL OR NOMBRE_CATEGORIA_ENTRADA IS NULL THEN
        IF CODIGO_CATEGORIA_ENTRADA IS NULL THEN
            RAISE CODIGO_CATEGORIA_ES_NULL;
        ELSE
            RAISE NOMBRE_CATEGORIA_ES_NULL;-- ESTO TAMBIEN PASA SI EL VARCHAR ES ''
        END IF;
    -- CODIGO CATEGORIA
    ELSIF REPETICION_CODIGO = 1 THEN
            RAISE CODIGO_YA_EN_USO;
    ELSIF CODIGO_CATEGORIA_ENTRADA <= 0 THEN
        RAISE CODIGO_INVALIDO;
    -- NOMBRE CATEGORIA
    ELSIF REPETICION_NOMBRE = 1 THEN
        RAISE NOMBRE_YA_EN_USO;
    ELSE
        INSERT INTO CATEGORIA VALUES(CODIGO_CATEGORIA_ENTRADA,NOMBRE_CATEGORIA_ENTRADA);
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('SE INSERTARON LOS DATOS EXITOSAMENTE');
    END IF;

    EXCEPTION
        -- NULL
        WHEN CODIGO_CATEGORIA_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('codigo categoria es null');
            ROLLBACK;
        WHEN NOMBRE_CATEGORIA_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('nombre de categoria es null');
            ROLLBACK;
        -- CODIGO CATEGORIA
        WHEN CODIGO_YA_EN_USO THEN
            DBMS_OUTPUT.PUT_LINE('EL CODIGO '||CODIGO_CATEGORIA_ENTRADA||' YA ESTA USADO');
            ROLLBACK;
        WHEN CODIGO_INVALIDO THEN
            DBMS_OUTPUT.PUT_LINE('DEBE INGRESAR NUMEROS POSITIVOS Y QUE NO ESTEN REPETIDOS');
            ROLLBACK;
        -- NOMBRE CATEGORIA
        WHEN NOMBRE_YA_EN_USO THEN
            DBMS_OUTPUT.PUT_LINE('Ese NOMBRE CATEGORIA: '||NOMBRE_CATEGORIA_ENTRADA||'YA ESTA SIENDO USADO');
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
