CREATE OR REPLACE PROCEDURE TRABAJO_2.INSERTAR_BOLETA(
    CODIGO_BOLETA_ENTRADA IN BOLETA.CODIGO_BOLETA%TYPE,
    RUT_ENTRADA IN BOLETA.RUT%TYPE,
    CODIGO_PRODUCTO_ENTRADA IN BOLETA.CODIGO_PRODUCTO%TYPE,
    FECHA_ENTRADA IN BOLETA.FECHA%TYPE,
    CANTIDAD_ENTRADA IN BOLETA.CANTIDAD%TYPE,
    TOTAL_ENTRADA IN BOLETA.TOTAL%TYPE
)
IS
    REPETICIONES_CODIGO_BOLETA NUMBER;
    REPETICIONES_RUT NUMBER;
    REPETICIONES_CODIGO_PRODUCTO NUMBER;
    DIA NUMBER;
    MES NUMBER;
    ANIO NUMBER;
    CODIGO_BOLETA_ES_NULL EXCEPTION;
    RUT_ES_NULL EXCEPTION;
    CODIGO_PRODUCTO_ES_NULL EXCEPTION;
    FECHA_ES_NULL EXCEPTION;
    CANTIDAD_ES_NULL EXCEPTION;
    TOTAL_ES_NULL EXCEPTION;
    CODIGO_BOLETA_INVALIDO EXCEPTION;
    CODIGO_BOLETA_YA_EN_USO EXCEPTION;
    CLIENTE_INEXISTENTE EXCEPTION;
    RUT_INVALIDO EXCEPTION;
    PRODUCTO_INEXISTENTE EXCEPTION;
    CODIGO_PRODUCTO_INVALUDO EXCEPTION;
    CANTIDAD_INVALIDA EXCEPTION;
    TOTAL_INVALIDO EXCEPTION;
BEGIN 
    LOCK TABLE BOLETA IN ROW EXCLUSIVE MODE;
    SELECT COUNT(*) INTO REPETICIONES_CODIGO_BOLETA
    FROM BOLETA
    WHERE CODIGO_BOLETA = CODIGO_BOLETA_ENTRADA;
    SELECT COUNT(*) INTO REPETICIONES_RUT
    FROM CLIENTE
    WHERE RUT = RUT_ENTRADA;
    SELECT COUNT(*) INTO REPETICIONES_CODIGO_PRODUCTO
    FROM PRODUCTO
    WHERE CODIGO_PRODUCTO = CODIGO_PRODUCTO_ENTRADA;
    -- NULL
    IF CODIGO_BOLETA_ENTRADA IS NULL OR RUT_ENTRADA IS NULL OR CODIGO_PRODUCTO_ENTRADA IS NULL OR FECHA_ENTRADA IS NULL OR CANTIDAD_ENTRADA IS NULL OR TOTAL_ENTRADA IS NULL THEN 
        IF CODIGO_BOLETA_ENTRADA IS NULL THEN
            RAISE CODIGO_BOLETA_ES_NULL;
        ELSIF RUT_ENTRADA IS NULL THEN  
            RAISE RUT_ES_NULL;
        ELSIF CODIGO_PRODUCTO_ENTRADA IS NULL THEN  
            RAISE CODIGO_PRODUCTO_ES_NULL;
        ELSIF FECHA_ENTRADA IS NULL THEN
            RAISE FECHA_ES_NULL;
        ELSIF CANTIDAD_ENTRADA IS NULL THEN     
            RAISE CANTIDAD_ES_NULL;
        ELSE    
            RAISE TOTAL_ES_NULL;        
        END IF;
    -- CODIGO BOLETA
    ELSIF CODIGO_BOLETA_ENTRADA < 1 THEN
        RAISE CODIGO_BOLETA_INVALIDO;
    ELSIF REPETICIONES_CODIGO_BOLETA = 1 THEN
        RAISE CODIGO_BOLETA_YA_EN_USO;
    -- RUT
    ELSIF REPETICIONES_RUT = 0 THEN
        RAISE CLIENTE_INEXISTENTE;
    ELSIF RUT_ENTRADA <= 4000000 OR RUT_ENTRADA >= 28000000 THEN
        RAISE RUT_INVALIDO;
    -- CODIGO PROFUCTO
    ELSIF REPETICIONES_CODIGO_PRODUCTO = 0 THEN
        RAISE PRODUCTO_INEXISTENTE;
    ELSIF CODIGO_PRODUCTO_ENTRADA < 1 THEN
        RAISE CODIGO_PRODUCTO_INVALUDO;
    -- FECHA
    -- CANTIDAD
    ELSIF CANTIDAD_ENTRADA < 1 THEN
        RAISE CANTIDAD_INVALIDA;
    -- TOTAL
    ELSIF TOTAL_ENTRADA < 1 THEN
        RAISE TOTAL_INVALIDO;
    ELSE
        INSERT INTO BOLETA VALUES(CODIGO_BOLETA_ENTRADA,RUT_ENTRADA,CODIGO_PRODUCTO_ENTRADA,FECHA_ENTRADA,CANTIDAD_ENTRADA,TOTAL_ENTRADA);
        DBMS_OUTPUT.PUT_LINE('SE INGRESARON LOS DATOS EN BOLETA');
        COMMIT;
    END IF;

    EXCEPTION
        WHEN CODIGO_BOLETA_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL CODIGO BOLETA ES NULL');
            ROLLBACK;
        WHEN RUT_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('RUT ES NULL');
            ROLLBACK;
        WHEN CODIGO_PRODUCTO_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL CODIGO DEL PRODUCTO ES NULL');
            ROLLBACK;
        WHEN FECHA_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('LA FECHA ES NULL');
            ROLLBACK;
        WHEN CANTIDAD_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE PRODUCTOS COMPRADOS ES NULL');
            ROLLBACK;
        WHEN TOTAL_ES_NULL THEN
            DBMS_OUTPUT.PUT_LINE('EL TOTAL ES NULL');
            ROLLBACK;
        WHEN CODIGO_BOLETA_INVALIDO THEN
            DBMS_OUTPUT.PUT_LINE('SE INGRESO UN CODIGO DE BOLETA INVALIDO');
            ROLLBACK;
        WHEN CODIGO_BOLETA_YA_EN_USO THEN
            DBMS_OUTPUT.PUT_LINE('ESE CODIGO DE BOLETA YA ESTA REGISTRADO');
            ROLLBACK;
        WHEN CLIENTE_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('ESE RUT NO ESTA EN LA BASE DE DATOS');
            ROLLBACK;
        WHEN RUT_INVALIDO THEN
            DBMS_OUTPUT.PUT_LINE('ESE RUT ES INVALIDO');
            ROLLBACK;
        WHEN PRODUCTO_INEXISTENTE THEN
            DBMS_OUTPUT.PUT_LINE('ESE PRODUCTO NO ESTA EN LA BASE DE DATOS');
            ROLLBACK;
        WHEN CODIGO_PRODUCTO_INVALUDO THEN
            DBMS_OUTPUT.PUT_LINE('NO SE PUEDE INGRESAR ESE CODIGO DE PROFUCTO');
            ROLLBACK;
        WHEN CANTIDAD_INVALIDA THEN
            DBMS_OUTPUT.PUT_LINE('LA BOLETA REGISTRA UNA COMPRA O MAS');
            ROLLBACK;
        WHEN TOTAL_INVALIDO THEN
            DBMS_OUTPUT.PUT_LINE('EL MONTO A PAGAR DEBE SER 1 O MAYOR');
            ROLLBACK;
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('ERROR NO IDENTIFICADO');
            ROLLBACK;
END;
