CREATE OR REPLACE ACTUALIZAR_NOMBRE_CATEGORIA(
    CODIGO_ENTRADA IN CATEGORIA.CODIGO_CATEGORIA%TYPE,
    NUEVO_NOMBRE IN CATEGORIA.NOMBRE_CATEGORIA%TYPE,
    MENSAJE OUT VARCHAR
)
IS 
    CODIGO_ES_NULL EXCEPTION;
    CODIGO_INEXISTENTE EXCEPTION;
    NOMBRE_ES_NULL EXCEPTION;
    NOMBRE_REPETIDO EXCEPTION;
    REPETICIONES NUMBER;
BEGIN
    LOCK TABLE CATEGORIA IN ROW EXCLUSIVE MODE;
    IF CODIGO_ENTRADA IS NULL THEN
        RAISE CODIGO_ES_NULL;
    ELSE
        SELECT COUNT(*) INTO REPETICIONES FROM CATEGORIA WHERE CODIGO_CATEGORIA = CODIGO_ENTRADA;
        IF REPETICIONES = 0 THEN
            RAISE CODIGO_INEXISTENTE;
        ELSE
            IF NUEVO_NOMBRE IS NULL THEN
                RAISE NOMBRE_ES_NULL;
            ELSE
                SELECT COUNT(*) INTO REPETICIONES FROM CATEGORIA WHERE NOMBRE_CATEGORIA = NUEVO_NOMBRE;
                IF REPETICIONES = 1 THEN
                    RAISE NOMBRE_REPETIDO;
                ELSE
                    UPDATE CATEGORIA SET NOMBRE_CATEGORIA = NUEVO_NOMBRE WHERE CODIGO_CATEGORIA = CODIGO_ENTRADA;
                    COMMIT;
                    MENSAJE := 'MIAU NOMBRE CATEGORIA';
                END IF;
            END IF;
        END IF;
    END IF;
EXCEPTION
    WHEN CODIGO_ES_NULL THEN
        MENSAJE := 'NO SE INGRESO EL CODIGO DE CATEGORIA';
        ROLLBACK;
    WHEN CODIGO_INEXISTENTE THEN
        MENSAJE := 'NO EXISTE ESE CODIGO DE CATEGORIA';
        ROLLBACK;
    WHEN NOMBRE_ES_NULL THEN
        MENSAJE := 'NO SE INGRESO EL NUEVO NOMBRE DE CATEGORIA';
        ROLLBACK;
    WHEN NOMBRE_REPETIDO THEN
        MENSAJE := 'ESE NOMBRE DE CATEGORIA YA ESTA REGISTADO';
        ROLLBACK;
    WHEN OTHERS THEN
        MENSAJE := 'ERROR AL CAMBIAR NOMBRE DE CATEGORIA';
        ROLLBACK;
END;